-- Ekwo OS — France: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/fr at version 1.2.0, do not edit.
-- Change the pack and run `ekwo pack build fr`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Maintained by Ekwo — not yet reviewed by an accountant.
-- Written from:
--   Règlement ANC 2022-06 — plan comptable général
--   Code général des impôts, art. 278, 278 bis, 278-0 bis, 281 quater
--   Formulaire 3310-CA3
--   Code general des impots, art. 298, 4 — produits petroliers
--   Code général des impôts, art. 269 — fait générateur et exigibilité
--   Code général des impôts, art. 262, I, 262 ter, I, 283 et 293 B — exonérations, autoliquidation et franchise en base
--   Code général des impôts, ann. II, art. 242 nonies A — mentions obligatoires et numérotation continue
--   Code de commerce, art. L441-9, L441-10 et D441-5 — délais de paiement, pénalités et indemnité forfaitaire
--   Ordonnance n° 2021-1190 du 15 septembre 2021 et loi de finances pour 2024, art. 91 — facturation électronique
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum)
values
  ('FR', 'France', '1.2.0', date '2026-09-12', '20260912111751', 'maintained', null, null, 'cb43d10ce80900c3435fd2656d27c8b358c9032ec28311d7c719c24d3547619c')
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum;

insert into chart_templates
  (country, code, name, name_i18n, is_default, audience, statements,
   certification_status, legal_reference)
values
  ('FR', 'default', 'PCG — plan comptable général', '{}'::jsonb, true, 'companies', array['FR-2050', 'FR-2052']::text[], null, 'Règlement ANC 2022-06 — plan comptable général')
on conflict (country, code) do update set
  name                 = excluded.name,
  name_i18n            = excluded.name_i18n,
  is_default           = excluded.is_default,
  audience             = excluded.audience,
  statements           = excluded.statements,
  certification_status = excluded.certification_status,
  legal_reference      = excluded.legal_reference;

insert into account_templates
  (country, chart_code, code, name, name_i18n, account_type, reconcilable,
   parent_code, sequence)
values
  ('FR', 'default', '10', 'Capital et réserves', '{}'::jsonb, 'equity', false, null, 10),
  ('FR', 'default', '101', 'Capital', '{}'::jsonb, 'equity', false, '10', 20),
  ('FR', 'default', '101000', 'Capital', '{}'::jsonb, 'equity', false, '101', 30),
  ('FR', 'default', '104', 'Primes liées au capital social', '{}'::jsonb, 'equity', false, '10', 40),
  ('FR', 'default', '104100', 'Primes d''émission', '{}'::jsonb, 'equity', false, '104', 50),
  ('FR', 'default', '105', 'Écarts de réévaluation', '{}'::jsonb, 'equity', false, '10', 60),
  ('FR', 'default', '106', 'Réserves', '{}'::jsonb, 'equity', false, '10', 70),
  ('FR', 'default', '106100', 'Réserve légale', '{}'::jsonb, 'equity', false, '106', 80),
  ('FR', 'default', '106300', 'Réserves statutaires ou contractuelles', '{}'::jsonb, 'equity', false, '106', 90),
  ('FR', 'default', '108', 'Compte de l''exploitant', '{}'::jsonb, 'equity', false, '10', 100),
  ('FR', 'default', '11', 'Report à nouveau', '{}'::jsonb, 'equity_retained', false, null, 110),
  ('FR', 'default', '110', 'Report à nouveau (solde créditeur)', '{}'::jsonb, 'equity_retained', false, '11', 120),
  ('FR', 'default', '110000', 'Report à nouveau créditeur', '{}'::jsonb, 'equity_retained', false, '110', 130),
  ('FR', 'default', '119', 'Report à nouveau (solde débiteur)', '{}'::jsonb, 'equity_retained', false, '11', 140),
  ('FR', 'default', '119000', 'Report à nouveau débiteur', '{}'::jsonb, 'equity_retained', false, '119', 150),
  ('FR', 'default', '12', 'Résultat de l''exercice', '{}'::jsonb, 'equity', false, null, 160),
  ('FR', 'default', '120', 'Résultat de l''exercice (bénéfice)', '{}'::jsonb, 'equity', false, '12', 170),
  ('FR', 'default', '120000', 'Résultat de l''exercice — bénéfice', '{}'::jsonb, 'equity', false, '120', 180),
  ('FR', 'default', '129', 'Résultat de l''exercice (perte)', '{}'::jsonb, 'equity', false, '12', 190),
  ('FR', 'default', '129000', 'Résultat de l''exercice — perte', '{}'::jsonb, 'equity', false, '129', 200),
  ('FR', 'default', '13', 'Subventions d''investissement', '{}'::jsonb, 'equity', false, null, 210),
  ('FR', 'default', '131', 'Subventions d''équipement', '{}'::jsonb, 'equity', false, '13', 220),
  ('FR', 'default', '131000', 'Subventions d''équipement reçues', '{}'::jsonb, 'equity', false, '131', 230),
  ('FR', 'default', '139', 'Subventions d''investissement inscrites au compte de résultat', '{}'::jsonb, 'equity', false, '13', 240),
  ('FR', 'default', '14', 'Provisions réglementées', '{}'::jsonb, 'equity', false, null, 250),
  ('FR', 'default', '145', 'Amortissements dérogatoires', '{}'::jsonb, 'equity', false, '14', 260),
  ('FR', 'default', '148', 'Autres provisions réglementées', '{}'::jsonb, 'equity', false, '14', 270),
  ('FR', 'default', '15', 'Provisions', '{}'::jsonb, 'liability_non_current', false, null, 280),
  ('FR', 'default', '151', 'Provisions pour risques', '{}'::jsonb, 'liability_non_current', false, '15', 290),
  ('FR', 'default', '151100', 'Provisions pour litiges', '{}'::jsonb, 'liability_non_current', false, '151', 300),
  ('FR', 'default', '153', 'Provisions pour pensions et obligations similaires', '{}'::jsonb, 'liability_non_current', false, '15', 310),
  ('FR', 'default', '155', 'Provisions pour impôts', '{}'::jsonb, 'liability_non_current', false, '15', 320),
  ('FR', 'default', '158', 'Autres provisions pour charges', '{}'::jsonb, 'liability_non_current', false, '15', 330),
  ('FR', 'default', '158000', 'Autres provisions pour charges', '{}'::jsonb, 'liability_non_current', false, '158', 340),
  ('FR', 'default', '16', 'Emprunts et dettes assimilées', '{}'::jsonb, 'liability_non_current', false, null, 350),
  ('FR', 'default', '161', 'Emprunts obligataires convertibles', '{}'::jsonb, 'liability_non_current', false, '16', 360),
  ('FR', 'default', '164', 'Emprunts auprès des établissements de crédit', '{}'::jsonb, 'liability_non_current', false, '16', 370),
  ('FR', 'default', '164000', 'Emprunts auprès des établissements de crédit', '{}'::jsonb, 'liability_non_current', false, '164', 380),
  ('FR', 'default', '165', 'Dépôts et cautionnements reçus', '{}'::jsonb, 'liability_non_current', false, '16', 390),
  ('FR', 'default', '166', 'Participation des salariés aux résultats', '{}'::jsonb, 'liability_non_current', false, '16', 400),
  ('FR', 'default', '167', 'Emprunts et dettes assortis de conditions particulières', '{}'::jsonb, 'liability_non_current', false, '16', 410),
  ('FR', 'default', '168', 'Autres emprunts et dettes assimilées', '{}'::jsonb, 'liability_non_current', false, '16', 420),
  ('FR', 'default', '168800', 'Intérêts courus sur emprunts et dettes', '{}'::jsonb, 'liability_non_current', false, '168', 430),
  ('FR', 'default', '17', 'Dettes rattachées à des participations', '{}'::jsonb, 'liability_non_current', false, null, 440),
  ('FR', 'default', '171', 'Dettes rattachées à des participations (groupe)', '{}'::jsonb, 'liability_non_current', false, '17', 450),
  ('FR', 'default', '18', 'Comptes de liaison des établissements et sociétés en participation', '{}'::jsonb, 'liability_non_current', false, null, 460),
  ('FR', 'default', '181', 'Comptes de liaison des établissements', '{}'::jsonb, 'liability_non_current', false, '18', 470),
  ('FR', 'default', '20', 'Immobilisations incorporelles', '{}'::jsonb, 'asset_fixed', false, null, 480),
  ('FR', 'default', '201', 'Frais d''établissement', '{}'::jsonb, 'asset_fixed', false, '20', 490),
  ('FR', 'default', '203', 'Frais de recherche et de développement', '{}'::jsonb, 'asset_fixed', false, '20', 500),
  ('FR', 'default', '205', 'Concessions, brevets, licences, marques, procédés et logiciels', '{}'::jsonb, 'asset_fixed', false, '20', 510),
  ('FR', 'default', '205000', 'Concessions, brevets et droits similaires', '{}'::jsonb, 'asset_fixed', false, '205', 520),
  ('FR', 'default', '205100', 'Logiciels', '{}'::jsonb, 'asset_fixed', false, '205', 530),
  ('FR', 'default', '206', 'Droit au bail', '{}'::jsonb, 'asset_fixed', false, '20', 540),
  ('FR', 'default', '207', 'Fonds commercial', '{}'::jsonb, 'asset_fixed', false, '20', 550),
  ('FR', 'default', '208', 'Autres immobilisations incorporelles', '{}'::jsonb, 'asset_fixed', false, '20', 560),
  ('FR', 'default', '21', 'Immobilisations corporelles', '{}'::jsonb, 'asset_fixed', false, null, 570),
  ('FR', 'default', '211', 'Terrains', '{}'::jsonb, 'asset_fixed', false, '21', 580),
  ('FR', 'default', '211000', 'Terrains', '{}'::jsonb, 'asset_fixed', false, '211', 590),
  ('FR', 'default', '213', 'Constructions', '{}'::jsonb, 'asset_fixed', false, '21', 600),
  ('FR', 'default', '213000', 'Constructions sur sol propre', '{}'::jsonb, 'asset_fixed', false, '213', 610),
  ('FR', 'default', '213500', 'Installations générales et agencements des constructions', '{}'::jsonb, 'asset_fixed', false, '213', 620),
  ('FR', 'default', '215', 'Installations techniques, matériel et outillage industriels', '{}'::jsonb, 'asset_fixed', false, '21', 630),
  ('FR', 'default', '215400', 'Matériel industriel', '{}'::jsonb, 'asset_fixed', false, '215', 640),
  ('FR', 'default', '218', 'Autres immobilisations corporelles', '{}'::jsonb, 'asset_fixed', false, '21', 650),
  ('FR', 'default', '218100', 'Installations générales, agencements et aménagements divers', '{}'::jsonb, 'asset_fixed', false, '218', 660),
  ('FR', 'default', '218200', 'Matériel de transport', '{}'::jsonb, 'asset_fixed', false, '218', 670),
  ('FR', 'default', '218300', 'Matériel de bureau et matériel informatique', '{}'::jsonb, 'asset_fixed', false, '218', 680),
  ('FR', 'default', '218400', 'Mobilier', '{}'::jsonb, 'asset_fixed', false, '218', 690),
  ('FR', 'default', '22', 'Immobilisations mises en concession', '{}'::jsonb, 'asset_fixed', false, null, 700),
  ('FR', 'default', '23', 'Immobilisations en cours', '{}'::jsonb, 'asset_fixed', false, null, 710),
  ('FR', 'default', '231', 'Immobilisations corporelles en cours', '{}'::jsonb, 'asset_fixed', false, '23', 720),
  ('FR', 'default', '232', 'Immobilisations incorporelles en cours', '{}'::jsonb, 'asset_fixed', false, '23', 730),
  ('FR', 'default', '237', 'Avances et acomptes versés sur immobilisations incorporelles', '{}'::jsonb, 'asset_fixed', false, '23', 740),
  ('FR', 'default', '238', 'Avances et acomptes versés sur immobilisations corporelles', '{}'::jsonb, 'asset_fixed', false, '23', 750),
  ('FR', 'default', '26', 'Participations et créances rattachées à des participations', '{}'::jsonb, 'asset_non_current', false, null, 760),
  ('FR', 'default', '261', 'Titres de participation', '{}'::jsonb, 'asset_non_current', false, '26', 770),
  ('FR', 'default', '261000', 'Titres de participation', '{}'::jsonb, 'asset_non_current', false, '261', 780),
  ('FR', 'default', '267', 'Créances rattachées à des participations', '{}'::jsonb, 'asset_non_current', false, '26', 790),
  ('FR', 'default', '27', 'Autres immobilisations financières', '{}'::jsonb, 'asset_non_current', false, null, 800),
  ('FR', 'default', '271', 'Titres immobilisés (droit de propriété)', '{}'::jsonb, 'asset_non_current', false, '27', 810),
  ('FR', 'default', '274', 'Prêts', '{}'::jsonb, 'asset_non_current', false, '27', 820),
  ('FR', 'default', '275', 'Dépôts et cautionnements versés', '{}'::jsonb, 'asset_non_current', false, '27', 830),
  ('FR', 'default', '275000', 'Dépôts et cautionnements versés', '{}'::jsonb, 'asset_non_current', false, '275', 840),
  ('FR', 'default', '276', 'Autres créances immobilisées', '{}'::jsonb, 'asset_non_current', false, '27', 850),
  ('FR', 'default', '28', 'Amortissements des immobilisations', '{}'::jsonb, 'asset_fixed', false, null, 860),
  ('FR', 'default', '280', 'Amortissements des immobilisations incorporelles', '{}'::jsonb, 'asset_fixed', false, '28', 870),
  ('FR', 'default', '280100', 'Amortissements des frais d''établissement', '{}'::jsonb, 'asset_fixed', false, '280', 880),
  ('FR', 'default', '280500', 'Amortissements des concessions, brevets et logiciels', '{}'::jsonb, 'asset_fixed', false, '280', 890),
  ('FR', 'default', '281', 'Amortissements des immobilisations corporelles', '{}'::jsonb, 'asset_fixed', false, '28', 900),
  ('FR', 'default', '281300', 'Amortissements des constructions', '{}'::jsonb, 'asset_fixed', false, '281', 910),
  ('FR', 'default', '281500', 'Amortissements des installations techniques et du matériel industriel', '{}'::jsonb, 'asset_fixed', false, '281', 920),
  ('FR', 'default', '281810', 'Amortissements des installations générales et agencements divers', '{}'::jsonb, 'asset_fixed', false, '281', 930),
  ('FR', 'default', '281820', 'Amortissements du matériel de transport', '{}'::jsonb, 'asset_fixed', false, '281', 940),
  ('FR', 'default', '281830', 'Amortissements du matériel de bureau et informatique', '{}'::jsonb, 'asset_fixed', false, '281', 950),
  ('FR', 'default', '281840', 'Amortissements du mobilier', '{}'::jsonb, 'asset_fixed', false, '281', 960),
  ('FR', 'default', '29', 'Dépréciations des immobilisations', '{}'::jsonb, 'asset_fixed', false, null, 970),
  ('FR', 'default', '290', 'Dépréciations des immobilisations incorporelles', '{}'::jsonb, 'asset_fixed', false, '29', 980),
  ('FR', 'default', '291', 'Dépréciations des immobilisations corporelles', '{}'::jsonb, 'asset_fixed', false, '29', 990),
  ('FR', 'default', '31', 'Matières premières et fournitures', '{}'::jsonb, 'asset_current', false, null, 1000),
  ('FR', 'default', '310', 'Matières premières', '{}'::jsonb, 'asset_current', false, '31', 1010),
  ('FR', 'default', '310000', 'Matières premières', '{}'::jsonb, 'asset_current', false, '310', 1020),
  ('FR', 'default', '317', 'Fournitures', '{}'::jsonb, 'asset_current', false, '31', 1030),
  ('FR', 'default', '32', 'Autres approvisionnements', '{}'::jsonb, 'asset_current', false, null, 1040),
  ('FR', 'default', '321', 'Matières consommables', '{}'::jsonb, 'asset_current', false, '32', 1050),
  ('FR', 'default', '322', 'Fournitures consommables', '{}'::jsonb, 'asset_current', false, '32', 1060),
  ('FR', 'default', '322500', 'Fournitures de bureau', '{}'::jsonb, 'asset_current', false, '322', 1070),
  ('FR', 'default', '326', 'Emballages', '{}'::jsonb, 'asset_current', false, '32', 1080),
  ('FR', 'default', '33', 'En-cours de production de biens', '{}'::jsonb, 'asset_current', false, null, 1090),
  ('FR', 'default', '331', 'Produits en cours', '{}'::jsonb, 'asset_current', false, '33', 1100),
  ('FR', 'default', '335', 'Travaux en cours', '{}'::jsonb, 'asset_current', false, '33', 1110),
  ('FR', 'default', '34', 'En-cours de production de services', '{}'::jsonb, 'asset_current', false, null, 1120),
  ('FR', 'default', '341', 'Études en cours', '{}'::jsonb, 'asset_current', false, '34', 1130),
  ('FR', 'default', '345', 'Prestations de services en cours', '{}'::jsonb, 'asset_current', false, '34', 1140),
  ('FR', 'default', '35', 'Stocks de produits', '{}'::jsonb, 'asset_current', false, null, 1150),
  ('FR', 'default', '351', 'Produits intermédiaires', '{}'::jsonb, 'asset_current', false, '35', 1160),
  ('FR', 'default', '355', 'Produits finis', '{}'::jsonb, 'asset_current', false, '35', 1170),
  ('FR', 'default', '355000', 'Produits finis', '{}'::jsonb, 'asset_current', false, '355', 1180),
  ('FR', 'default', '358', 'Produits résiduels', '{}'::jsonb, 'asset_current', false, '35', 1190),
  ('FR', 'default', '37', 'Stocks de marchandises', '{}'::jsonb, 'asset_current', false, null, 1200),
  ('FR', 'default', '370', 'Stocks de marchandises', '{}'::jsonb, 'asset_current', false, '37', 1210),
  ('FR', 'default', '370000', 'Stocks de marchandises', '{}'::jsonb, 'asset_current', false, '370', 1220),
  ('FR', 'default', '39', 'Dépréciations des stocks et en-cours', '{}'::jsonb, 'asset_current', false, null, 1230),
  ('FR', 'default', '391', 'Dépréciations des matières premières et fournitures', '{}'::jsonb, 'asset_current', false, '39', 1240),
  ('FR', 'default', '397', 'Dépréciations des stocks de marchandises', '{}'::jsonb, 'asset_current', false, '39', 1250),
  ('FR', 'default', '397000', 'Dépréciations des stocks de marchandises', '{}'::jsonb, 'asset_current', false, '397', 1260),
  ('FR', 'default', '40', 'Fournisseurs et comptes rattachés', '{}'::jsonb, 'liability_payable', true, null, 1270),
  ('FR', 'default', '401', 'Fournisseurs', '{}'::jsonb, 'liability_payable', true, '40', 1280),
  ('FR', 'default', '401000', 'Fournisseurs', '{}'::jsonb, 'liability_payable', true, '401', 1290),
  ('FR', 'default', '401100', 'Fournisseurs — achats de biens et prestations de services', '{}'::jsonb, 'liability_payable', true, '401', 1300),
  ('FR', 'default', '403', 'Fournisseurs — Effets à payer', '{}'::jsonb, 'liability_current', false, '40', 1310),
  ('FR', 'default', '404', 'Fournisseurs d''immobilisations', '{}'::jsonb, 'liability_current', false, '40', 1320),
  ('FR', 'default', '405', 'Fournisseurs d''immobilisations — Effets à payer', '{}'::jsonb, 'liability_current', false, '40', 1330),
  ('FR', 'default', '408', 'Fournisseurs — Factures non parvenues', '{}'::jsonb, 'liability_current', false, '40', 1340),
  ('FR', 'default', '408100', 'Fournisseurs — factures non parvenues', '{}'::jsonb, 'liability_current', false, '408', 1350),
  ('FR', 'default', '409', 'Fournisseurs débiteurs', '{}'::jsonb, 'liability_current', false, '40', 1360),
  ('FR', 'default', '409100', 'Fournisseurs — avances et acomptes versés sur commandes', '{}'::jsonb, 'liability_current', false, '409', 1370),
  ('FR', 'default', '41', 'Clients et comptes rattachés', '{}'::jsonb, 'asset_receivable', true, null, 1380),
  ('FR', 'default', '411', 'Clients', '{}'::jsonb, 'asset_receivable', true, '41', 1390),
  ('FR', 'default', '411000', 'Clients — ventes de biens et prestations de services', '{}'::jsonb, 'asset_receivable', true, '411', 1400),
  ('FR', 'default', '413', 'Clients — Effets à recevoir', '{}'::jsonb, 'asset_current', false, '41', 1410),
  ('FR', 'default', '416', 'Clients douteux ou litigieux', '{}'::jsonb, 'asset_current', false, '41', 1420),
  ('FR', 'default', '416000', 'Clients douteux ou litigieux', '{}'::jsonb, 'asset_current', false, '416', 1430),
  ('FR', 'default', '418', 'Clients — Produits non encore facturés', '{}'::jsonb, 'asset_current', false, '41', 1440),
  ('FR', 'default', '418100', 'Clients — factures à établir', '{}'::jsonb, 'asset_current', false, '418', 1450),
  ('FR', 'default', '419', 'Clients créditeurs', '{}'::jsonb, 'asset_current', false, '41', 1460),
  ('FR', 'default', '419100', 'Clients — avances et acomptes reçus sur commandes', '{}'::jsonb, 'asset_current', false, '419', 1470),
  ('FR', 'default', '42', 'Personnel et comptes rattachés', '{}'::jsonb, 'liability_current', false, null, 1480),
  ('FR', 'default', '421', 'Personnel — Rémunérations dues', '{}'::jsonb, 'liability_current', false, '42', 1490),
  ('FR', 'default', '421000', 'Personnel — rémunérations dues', '{}'::jsonb, 'liability_current', false, '421', 1500),
  ('FR', 'default', '425', 'Personnel — Avances et acomptes', '{}'::jsonb, 'liability_current', false, '42', 1510),
  ('FR', 'default', '425000', 'Personnel — avances et acomptes', '{}'::jsonb, 'liability_current', false, '425', 1520),
  ('FR', 'default', '427', 'Personnel — Oppositions', '{}'::jsonb, 'liability_current', false, '42', 1530),
  ('FR', 'default', '428', 'Personnel — Charges à payer et produits à recevoir', '{}'::jsonb, 'liability_current', false, '42', 1540),
  ('FR', 'default', '428200', 'Dettes provisionnées pour congés à payer', '{}'::jsonb, 'liability_current', false, '428', 1550),
  ('FR', 'default', '428600', 'Personnel — autres charges à payer', '{}'::jsonb, 'liability_current', false, '428', 1560),
  ('FR', 'default', '43', 'Sécurité sociale et autres organismes sociaux', '{}'::jsonb, 'liability_current', false, null, 1570),
  ('FR', 'default', '431', 'Sécurité sociale', '{}'::jsonb, 'liability_current', false, '43', 1580),
  ('FR', 'default', '431000', 'URSSAF — cotisations à payer', '{}'::jsonb, 'liability_current', false, '431', 1590),
  ('FR', 'default', '437', 'Autres organismes sociaux', '{}'::jsonb, 'liability_current', false, '43', 1600),
  ('FR', 'default', '437100', 'Caisses de retraite complémentaire', '{}'::jsonb, 'liability_current', false, '437', 1610),
  ('FR', 'default', '437200', 'Mutuelle et organismes de prévoyance', '{}'::jsonb, 'liability_current', false, '437', 1620),
  ('FR', 'default', '438', 'Organismes sociaux — Charges à payer et produits à recevoir', '{}'::jsonb, 'liability_current', false, '43', 1630),
  ('FR', 'default', '44', 'État et autres collectivités publiques', '{}'::jsonb, 'liability_current', false, null, 1640),
  ('FR', 'default', '441', 'État — Subventions à recevoir', '{}'::jsonb, 'asset_current', false, '44', 1650),
  ('FR', 'default', '444', 'État — Impôt sur les bénéfices', '{}'::jsonb, 'liability_current', false, '44', 1660),
  ('FR', 'default', '444000', 'État — impôt sur les bénéfices', '{}'::jsonb, 'liability_current', false, '444', 1670),
  ('FR', 'default', '445', 'État — Taxes sur le chiffre d''affaires', '{}'::jsonb, 'liability_current', false, '44', 1680),
  ('FR', 'default', '445200', 'TVA due intracommunautaire', '{}'::jsonb, 'liability_current', false, '445', 1690),
  ('FR', 'default', '445510', 'TVA à décaisser', '{}'::jsonb, 'liability_current', false, '445', 1700),
  ('FR', 'default', '445660', 'TVA déductible sur autres biens et services', '{}'::jsonb, 'asset_current', false, '445', 1710),
  ('FR', 'default', '445662', 'TVA déductible sur immobilisations', '{}'::jsonb, 'asset_current', false, '445', 1720),
  ('FR', 'default', '445670', 'Crédit de TVA à reporter', '{}'::jsonb, 'asset_current', false, '445', 1730),
  ('FR', 'default', '445710', 'TVA collectée', '{}'::jsonb, 'liability_current', false, '445', 1740),
  ('FR', 'default', '445800', 'Taxes sur le chiffre d''affaires à régulariser ou en attente', '{}'::jsonb, 'asset_current', false, '445', 1750),
  ('FR', 'default', '447', 'Autres impôts, taxes et versements assimilés', '{}'::jsonb, 'liability_current', false, '44', 1760),
  ('FR', 'default', '447000', 'Autres impôts, taxes et versements assimilés', '{}'::jsonb, 'liability_current', false, '447', 1770),
  ('FR', 'default', '448', 'État — Charges à payer et produits à recevoir', '{}'::jsonb, 'liability_current', false, '44', 1780),
  ('FR', 'default', '45', 'Groupe et associés', '{}'::jsonb, 'liability_current', false, null, 1790),
  ('FR', 'default', '451', 'Groupe', '{}'::jsonb, 'liability_current', false, '45', 1800),
  ('FR', 'default', '455', 'Associés — Comptes courants', '{}'::jsonb, 'liability_current', false, '45', 1810),
  ('FR', 'default', '455000', 'Associés — comptes courants', '{}'::jsonb, 'liability_current', false, '455', 1820),
  ('FR', 'default', '456', 'Associés — Opérations sur le capital', '{}'::jsonb, 'liability_current', false, '45', 1830),
  ('FR', 'default', '457', 'Associés — Dividendes à payer', '{}'::jsonb, 'liability_current', false, '45', 1840),
  ('FR', 'default', '457000', 'Associés — dividendes à payer', '{}'::jsonb, 'liability_current', false, '457', 1850),
  ('FR', 'default', '46', 'Débiteurs divers et créditeurs divers', '{}'::jsonb, 'liability_current', false, null, 1860),
  ('FR', 'default', '462', 'Créances sur cessions d''immobilisations', '{}'::jsonb, 'asset_current', false, '46', 1870),
  ('FR', 'default', '465', 'Créances sur cessions de valeurs mobilières de placement', '{}'::jsonb, 'asset_current', false, '46', 1880),
  ('FR', 'default', '467', 'Autres comptes débiteurs ou créditeurs', '{}'::jsonb, 'liability_current', false, '46', 1890),
  ('FR', 'default', '467000', 'Autres comptes débiteurs ou créditeurs', '{}'::jsonb, 'liability_current', false, '467', 1900),
  ('FR', 'default', '468', 'Divers — Charges à payer et produits à recevoir', '{}'::jsonb, 'liability_current', false, '46', 1910),
  ('FR', 'default', '468600', 'Divers — charges à payer', '{}'::jsonb, 'liability_current', false, '468', 1920),
  ('FR', 'default', '47', 'Comptes transitoires ou d''attente', '{}'::jsonb, 'liability_current', false, null, 1930),
  ('FR', 'default', '471', 'Comptes d''attente', '{}'::jsonb, 'liability_current', false, '47', 1940),
  ('FR', 'default', '471000', 'Compte d''attente', '{}'::jsonb, 'liability_current', false, '471', 1950),
  ('FR', 'default', '478', 'Autres comptes transitoires', '{}'::jsonb, 'liability_current', false, '47', 1960),
  ('FR', 'default', '48', 'Comptes de régularisation', '{}'::jsonb, 'liability_current', false, null, 1970),
  ('FR', 'default', '486', 'Charges constatées d''avance', '{}'::jsonb, 'asset_prepayments', false, '48', 1980),
  ('FR', 'default', '486000', 'Charges constatées d''avance', '{}'::jsonb, 'asset_prepayments', false, '486', 1990),
  ('FR', 'default', '487', 'Produits constatés d''avance', '{}'::jsonb, 'liability_current', false, '48', 2000),
  ('FR', 'default', '487000', 'Produits constatés d''avance', '{}'::jsonb, 'liability_current', false, '487', 2010),
  ('FR', 'default', '49', 'Dépréciations des comptes de tiers', '{}'::jsonb, 'asset_current', false, null, 2020),
  ('FR', 'default', '491', 'Dépréciations des comptes de clients', '{}'::jsonb, 'asset_current', false, '49', 2030),
  ('FR', 'default', '491000', 'Dépréciations des comptes de clients', '{}'::jsonb, 'asset_current', false, '491', 2040),
  ('FR', 'default', '50', 'Valeurs mobilières de placement', '{}'::jsonb, 'asset_current', false, null, 2050),
  ('FR', 'default', '501', 'Parts dans des entreprises liées', '{}'::jsonb, 'asset_current', false, '50', 2060),
  ('FR', 'default', '503', 'Actions', '{}'::jsonb, 'asset_current', false, '50', 2070),
  ('FR', 'default', '506', 'Obligations', '{}'::jsonb, 'asset_current', false, '50', 2080),
  ('FR', 'default', '508', 'Autres valeurs mobilières de placement et créances assimilées', '{}'::jsonb, 'asset_current', false, '50', 2090),
  ('FR', 'default', '51', 'Banques, établissements financiers et assimilés', '{}'::jsonb, 'asset_current', false, null, 2100),
  ('FR', 'default', '511', 'Valeurs à l''encaissement', '{}'::jsonb, 'asset_current', false, '51', 2110),
  ('FR', 'default', '511300', 'Chèques à encaisser', '{}'::jsonb, 'asset_current', false, '511', 2120),
  ('FR', 'default', '512', 'Banques', '{}'::jsonb, 'asset_cash', false, '51', 2130),
  ('FR', 'default', '512000', 'Banque', '{}'::jsonb, 'asset_cash', false, '512', 2140),
  ('FR', 'default', '512100', 'Banque — compte courant', '{}'::jsonb, 'asset_cash', false, '512', 2150),
  ('FR', 'default', '512500', 'Banque — compte en devises', '{}'::jsonb, 'asset_cash', false, '512', 2160),
  ('FR', 'default', '514', 'Chèques postaux', '{}'::jsonb, 'asset_current', false, '51', 2170),
  ('FR', 'default', '517', 'Autres organismes financiers', '{}'::jsonb, 'asset_current', false, '51', 2180),
  ('FR', 'default', '518', 'Intérêts courus', '{}'::jsonb, 'asset_current', false, '51', 2190),
  ('FR', 'default', '52', 'Instruments de trésorerie', '{}'::jsonb, 'asset_current', false, null, 2200),
  ('FR', 'default', '53', 'Caisse', '{}'::jsonb, 'asset_cash', false, null, 2210),
  ('FR', 'default', '530', 'Caisse', '{}'::jsonb, 'asset_cash', false, '53', 2220),
  ('FR', 'default', '530000', 'Caisse', '{}'::jsonb, 'asset_cash', false, '530', 2230),
  ('FR', 'default', '54', 'Régies d''avances et accréditifs', '{}'::jsonb, 'asset_current', false, null, 2240),
  ('FR', 'default', '540', 'Régies d''avances et accréditifs', '{}'::jsonb, 'asset_current', false, '54', 2250),
  ('FR', 'default', '58', 'Virements internes', '{}'::jsonb, 'asset_current', false, null, 2260),
  ('FR', 'default', '580', 'Virements internes', '{}'::jsonb, 'asset_current', false, '58', 2270),
  ('FR', 'default', '580000', 'Virements internes', '{}'::jsonb, 'asset_current', false, '580', 2280),
  ('FR', 'default', '59', 'Dépréciations des comptes financiers', '{}'::jsonb, 'asset_current', false, null, 2290),
  ('FR', 'default', '590', 'Dépréciations des valeurs mobilières de placement', '{}'::jsonb, 'asset_current', false, '59', 2300),
  ('FR', 'default', '60', 'Achats', '{}'::jsonb, 'expense_direct_cost', false, null, 2310),
  ('FR', 'default', '601', 'Achats stockés — Matières premières et fournitures', '{}'::jsonb, 'expense_direct_cost', false, '60', 2320),
  ('FR', 'default', '601000', 'Achats de matières premières', '{}'::jsonb, 'expense_direct_cost', false, '601', 2330),
  ('FR', 'default', '602', 'Achats stockés — Autres approvisionnements', '{}'::jsonb, 'expense_direct_cost', false, '60', 2340),
  ('FR', 'default', '603', 'Variation des stocks', '{}'::jsonb, 'expense_direct_cost', false, '60', 2350),
  ('FR', 'default', '603100', 'Variation des stocks de matières premières', '{}'::jsonb, 'expense_direct_cost', false, '603', 2360),
  ('FR', 'default', '603700', 'Variation des stocks de marchandises', '{}'::jsonb, 'expense_direct_cost', false, '603', 2370),
  ('FR', 'default', '604', 'Achats d''études et prestations de services', '{}'::jsonb, 'expense_direct_cost', false, '60', 2380),
  ('FR', 'default', '605', 'Achats de matériel, équipements et travaux', '{}'::jsonb, 'expense_direct_cost', false, '60', 2390),
  ('FR', 'default', '606', 'Achats non stockés de matières et fournitures', '{}'::jsonb, 'expense_direct_cost', false, '60', 2400),
  ('FR', 'default', '606100', 'Fournitures non stockables — eau et énergie', '{}'::jsonb, 'expense_direct_cost', false, '606', 2410),
  ('FR', 'default', '606300', 'Fournitures d''entretien et de petit équipement', '{}'::jsonb, 'expense_direct_cost', false, '606', 2420),
  ('FR', 'default', '606400', 'Fournitures administratives', '{}'::jsonb, 'expense_direct_cost', false, '606', 2430),
  ('FR', 'default', '607', 'Achats de marchandises', '{}'::jsonb, 'expense_direct_cost', false, '60', 2440),
  ('FR', 'default', '607000', 'Achats de marchandises', '{}'::jsonb, 'expense_direct_cost', false, '607', 2450),
  ('FR', 'default', '608', 'Frais accessoires d''achat', '{}'::jsonb, 'expense_direct_cost', false, '60', 2460),
  ('FR', 'default', '609', 'Rabais, remises et ristournes obtenus sur achats', '{}'::jsonb, 'expense_direct_cost', false, '60', 2470),
  ('FR', 'default', '61', 'Services extérieurs', '{}'::jsonb, 'expense', false, null, 2480),
  ('FR', 'default', '611', 'Sous-traitance générale', '{}'::jsonb, 'expense', false, '61', 2490),
  ('FR', 'default', '611000', 'Sous-traitance générale', '{}'::jsonb, 'expense', false, '611', 2500),
  ('FR', 'default', '612', 'Redevances de crédit-bail', '{}'::jsonb, 'expense', false, '61', 2510),
  ('FR', 'default', '613', 'Locations', '{}'::jsonb, 'expense', false, '61', 2520),
  ('FR', 'default', '613200', 'Locations immobilières', '{}'::jsonb, 'expense', false, '613', 2530),
  ('FR', 'default', '613500', 'Locations mobilières', '{}'::jsonb, 'expense', false, '613', 2540),
  ('FR', 'default', '614', 'Charges locatives et de copropriété', '{}'::jsonb, 'expense', false, '61', 2550),
  ('FR', 'default', '615', 'Entretien et réparations', '{}'::jsonb, 'expense', false, '61', 2560),
  ('FR', 'default', '615200', 'Entretien et réparations sur biens immobiliers', '{}'::jsonb, 'expense', false, '615', 2570),
  ('FR', 'default', '615500', 'Entretien et réparations sur biens mobiliers', '{}'::jsonb, 'expense', false, '615', 2580),
  ('FR', 'default', '615600', 'Maintenance', '{}'::jsonb, 'expense', false, '615', 2590),
  ('FR', 'default', '616', 'Primes d''assurances', '{}'::jsonb, 'expense', false, '61', 2600),
  ('FR', 'default', '616000', 'Primes d''assurances', '{}'::jsonb, 'expense', false, '616', 2610),
  ('FR', 'default', '617', 'Études et recherches', '{}'::jsonb, 'expense', false, '61', 2620),
  ('FR', 'default', '618', 'Divers', '{}'::jsonb, 'expense', false, '61', 2630),
  ('FR', 'default', '618100', 'Documentation générale', '{}'::jsonb, 'expense', false, '618', 2640),
  ('FR', 'default', '619', 'Rabais, remises et ristournes obtenus sur services extérieurs', '{}'::jsonb, 'expense', false, '61', 2650),
  ('FR', 'default', '62', 'Autres services extérieurs', '{}'::jsonb, 'expense', false, null, 2660),
  ('FR', 'default', '621', 'Personnel extérieur à l''entreprise', '{}'::jsonb, 'expense', false, '62', 2670),
  ('FR', 'default', '622', 'Rémunérations d''intermédiaires et honoraires', '{}'::jsonb, 'expense', false, '62', 2680),
  ('FR', 'default', '622600', 'Honoraires', '{}'::jsonb, 'expense', false, '622', 2690),
  ('FR', 'default', '622700', 'Frais d''actes et de contentieux', '{}'::jsonb, 'expense', false, '622', 2700),
  ('FR', 'default', '623', 'Publicité, publications et relations publiques', '{}'::jsonb, 'expense', false, '62', 2710),
  ('FR', 'default', '623100', 'Annonces et insertions', '{}'::jsonb, 'expense', false, '623', 2720),
  ('FR', 'default', '624', 'Transports de biens et transports collectifs du personnel', '{}'::jsonb, 'expense', false, '62', 2730),
  ('FR', 'default', '625', 'Déplacements, missions et réceptions', '{}'::jsonb, 'expense', false, '62', 2740),
  ('FR', 'default', '625100', 'Voyages et déplacements', '{}'::jsonb, 'expense', false, '625', 2750),
  ('FR', 'default', '625600', 'Missions', '{}'::jsonb, 'expense', false, '625', 2760),
  ('FR', 'default', '625700', 'Réceptions', '{}'::jsonb, 'expense', false, '625', 2770),
  ('FR', 'default', '626', 'Frais postaux et de télécommunications', '{}'::jsonb, 'expense', false, '62', 2780),
  ('FR', 'default', '626100', 'Frais de télécommunications', '{}'::jsonb, 'expense', false, '626', 2790),
  ('FR', 'default', '627', 'Services bancaires et assimilés', '{}'::jsonb, 'expense', false, '62', 2800),
  ('FR', 'default', '627000', 'Services bancaires et assimilés', '{}'::jsonb, 'expense', false, '627', 2810),
  ('FR', 'default', '628', 'Divers', '{}'::jsonb, 'expense', false, '62', 2820),
  ('FR', 'default', '628100', 'Concours divers — cotisations', '{}'::jsonb, 'expense', false, '628', 2830),
  ('FR', 'default', '629', 'Rabais, remises et ristournes obtenus sur autres services extérieurs', '{}'::jsonb, 'expense', false, '62', 2840),
  ('FR', 'default', '63', 'Impôts, taxes et versements assimilés', '{}'::jsonb, 'expense', false, null, 2850),
  ('FR', 'default', '631', 'Impôts et taxes sur rémunérations (administration des impôts)', '{}'::jsonb, 'expense', false, '63', 2860),
  ('FR', 'default', '633', 'Impôts et taxes sur rémunérations (autres organismes)', '{}'::jsonb, 'expense', false, '63', 2870),
  ('FR', 'default', '633300', 'Formation professionnelle continue', '{}'::jsonb, 'expense', false, '633', 2880),
  ('FR', 'default', '635', 'Autres impôts et taxes (administration des impôts)', '{}'::jsonb, 'expense', false, '63', 2890),
  ('FR', 'default', '635100', 'Contribution économique territoriale', '{}'::jsonb, 'expense', false, '635', 2900),
  ('FR', 'default', '637', 'Autres impôts et taxes (autres organismes)', '{}'::jsonb, 'expense', false, '63', 2910),
  ('FR', 'default', '64', 'Charges de personnel', '{}'::jsonb, 'expense', false, null, 2920),
  ('FR', 'default', '641', 'Rémunérations du personnel', '{}'::jsonb, 'expense', false, '64', 2930),
  ('FR', 'default', '641000', 'Rémunérations du personnel', '{}'::jsonb, 'expense', false, '641', 2940),
  ('FR', 'default', '641100', 'Salaires et appointements', '{}'::jsonb, 'expense', false, '641', 2950),
  ('FR', 'default', '641400', 'Indemnités et avantages divers', '{}'::jsonb, 'expense', false, '641', 2960),
  ('FR', 'default', '644', 'Rémunération du travail de l''exploitant', '{}'::jsonb, 'expense', false, '64', 2970),
  ('FR', 'default', '645', 'Charges de sécurité sociale et de prévoyance', '{}'::jsonb, 'expense', false, '64', 2980),
  ('FR', 'default', '645100', 'Cotisations à l''URSSAF', '{}'::jsonb, 'expense', false, '645', 2990),
  ('FR', 'default', '645300', 'Cotisations aux caisses de retraite', '{}'::jsonb, 'expense', false, '645', 3000),
  ('FR', 'default', '647', 'Autres charges sociales', '{}'::jsonb, 'expense', false, '64', 3010),
  ('FR', 'default', '647500', 'Médecine du travail et pharmacie', '{}'::jsonb, 'expense', false, '647', 3020),
  ('FR', 'default', '648', 'Autres charges de personnel', '{}'::jsonb, 'expense', false, '64', 3030),
  ('FR', 'default', '65', 'Autres charges de gestion courante', '{}'::jsonb, 'expense', false, null, 3040),
  ('FR', 'default', '651', 'Redevances pour concessions, brevets, licences et marques', '{}'::jsonb, 'expense', false, '65', 3050),
  ('FR', 'default', '653', 'Jetons de présence', '{}'::jsonb, 'expense', false, '65', 3060),
  ('FR', 'default', '654', 'Pertes sur créances irrécouvrables', '{}'::jsonb, 'expense', false, '65', 3070),
  ('FR', 'default', '655', 'Quote-part de résultat sur opérations faites en commun', '{}'::jsonb, 'expense', false, '65', 3080),
  ('FR', 'default', '658', 'Charges diverses de gestion courante', '{}'::jsonb, 'expense', false, '65', 3090),
  ('FR', 'default', '658000', 'Charges diverses de gestion courante', '{}'::jsonb, 'expense', false, '658', 3100),
  ('FR', 'default', '66', 'Charges financières', '{}'::jsonb, 'expense', false, null, 3110),
  ('FR', 'default', '661', 'Charges d''intérêts', '{}'::jsonb, 'expense', false, '66', 3120),
  ('FR', 'default', '661600', 'Intérêts des emprunts et dettes', '{}'::jsonb, 'expense', false, '661', 3130),
  ('FR', 'default', '664', 'Pertes sur créances liées à des participations', '{}'::jsonb, 'expense', false, '66', 3140),
  ('FR', 'default', '665', 'Escomptes accordés', '{}'::jsonb, 'expense', false, '66', 3150),
  ('FR', 'default', '666', 'Pertes de change', '{}'::jsonb, 'expense', false, '66', 3160),
  ('FR', 'default', '666000', 'Pertes de change', '{}'::jsonb, 'expense', false, '666', 3170),
  ('FR', 'default', '667', 'Charges nettes sur cessions de valeurs mobilières de placement', '{}'::jsonb, 'expense', false, '66', 3180),
  ('FR', 'default', '668', 'Autres charges financières', '{}'::jsonb, 'expense', false, '66', 3190),
  ('FR', 'default', '67', 'Charges exceptionnelles', '{}'::jsonb, 'expense', false, null, 3200),
  ('FR', 'default', '671', 'Charges exceptionnelles sur opérations de gestion', '{}'::jsonb, 'expense', false, '67', 3210),
  ('FR', 'default', '671200', 'Pénalités, amendes fiscales et pénales', '{}'::jsonb, 'expense', false, '671', 3220),
  ('FR', 'default', '675', 'Valeurs comptables des éléments d''actif cédés', '{}'::jsonb, 'expense', false, '67', 3230),
  ('FR', 'default', '675000', 'Valeurs comptables des éléments d''actif cédés', '{}'::jsonb, 'expense', false, '675', 3240),
  ('FR', 'default', '678', 'Autres charges exceptionnelles', '{}'::jsonb, 'expense', false, '67', 3250),
  ('FR', 'default', '68', 'Dotations aux amortissements, dépréciations et provisions', '{}'::jsonb, 'expense_depreciation', false, null, 3260),
  ('FR', 'default', '681', 'Dotations aux amortissements et provisions — charges d''exploitation', '{}'::jsonb, 'expense_depreciation', false, '68', 3270),
  ('FR', 'default', '681100', 'Dotations aux amortissements sur immobilisations', '{}'::jsonb, 'expense_depreciation', false, '681', 3280),
  ('FR', 'default', '681500', 'Dotations aux provisions pour risques et charges d''exploitation', '{}'::jsonb, 'expense_depreciation', false, '681', 3290),
  ('FR', 'default', '681700', 'Dotations aux dépréciations des actifs circulants', '{}'::jsonb, 'expense_depreciation', false, '681', 3300),
  ('FR', 'default', '686', 'Dotations aux amortissements et provisions — charges financières', '{}'::jsonb, 'expense_depreciation', false, '68', 3310),
  ('FR', 'default', '687', 'Dotations aux amortissements et provisions — charges exceptionnelles', '{}'::jsonb, 'expense_depreciation', false, '68', 3320),
  ('FR', 'default', '687200', 'Dotations aux amortissements dérogatoires', '{}'::jsonb, 'expense_depreciation', false, '687', 3330),
  ('FR', 'default', '69', 'Participation des salariés et impôts sur les bénéfices', '{}'::jsonb, 'expense', false, null, 3340),
  ('FR', 'default', '691', 'Participation des salariés aux résultats', '{}'::jsonb, 'expense', false, '69', 3350),
  ('FR', 'default', '695', 'Impôts sur les bénéfices', '{}'::jsonb, 'expense', false, '69', 3360),
  ('FR', 'default', '695000', 'Impôts sur les bénéfices', '{}'::jsonb, 'expense', false, '695', 3370),
  ('FR', 'default', '696', 'Suppléments d''impôt sur les sociétés liés aux distributions', '{}'::jsonb, 'expense', false, '69', 3380),
  ('FR', 'default', '698', 'Intégration fiscale', '{}'::jsonb, 'expense', false, '69', 3390),
  ('FR', 'default', '70', 'Ventes de produits fabriqués, prestations de services, marchandises', '{}'::jsonb, 'income', false, null, 3400),
  ('FR', 'default', '701', 'Ventes de produits finis', '{}'::jsonb, 'income', false, '70', 3410),
  ('FR', 'default', '704', 'Travaux', '{}'::jsonb, 'income', false, '70', 3420),
  ('FR', 'default', '704000', 'Travaux', '{}'::jsonb, 'income', false, '704', 3430),
  ('FR', 'default', '705', 'Études', '{}'::jsonb, 'income', false, '70', 3440),
  ('FR', 'default', '705000', 'Études', '{}'::jsonb, 'income', false, '705', 3450),
  ('FR', 'default', '706', 'Prestations de services', '{}'::jsonb, 'income', false, '70', 3460),
  ('FR', 'default', '706000', 'Prestations de services', '{}'::jsonb, 'income', false, '706', 3470),
  ('FR', 'default', '707', 'Ventes de marchandises', '{}'::jsonb, 'income', false, '70', 3480),
  ('FR', 'default', '707000', 'Ventes de marchandises', '{}'::jsonb, 'income', false, '707', 3490),
  ('FR', 'default', '708', 'Produits des activités annexes', '{}'::jsonb, 'income', false, '70', 3500),
  ('FR', 'default', '708500', 'Ports et frais accessoires facturés', '{}'::jsonb, 'income', false, '708', 3510),
  ('FR', 'default', '709', 'Rabais, remises et ristournes accordés par l''entreprise', '{}'::jsonb, 'income', false, '70', 3520),
  ('FR', 'default', '709000', 'Rabais, remises et ristournes accordés', '{}'::jsonb, 'income', false, '709', 3530),
  ('FR', 'default', '71', 'Production stockée (ou déstockage)', '{}'::jsonb, 'income_other', false, null, 3540),
  ('FR', 'default', '713', 'Variation des stocks (en-cours de production, produits)', '{}'::jsonb, 'income_other', false, '71', 3550),
  ('FR', 'default', '713500', 'Variation des stocks de produits finis', '{}'::jsonb, 'income_other', false, '713', 3560),
  ('FR', 'default', '72', 'Production immobilisée', '{}'::jsonb, 'income_other', false, null, 3570),
  ('FR', 'default', '721', 'Production immobilisée — immobilisations incorporelles', '{}'::jsonb, 'income_other', false, '72', 3580),
  ('FR', 'default', '722', 'Production immobilisée — immobilisations corporelles', '{}'::jsonb, 'income_other', false, '72', 3590),
  ('FR', 'default', '73', 'Produits nets partiels sur opérations à long terme', '{}'::jsonb, 'income_other', false, null, 3600),
  ('FR', 'default', '734', 'Produits nets sur opérations à long terme', '{}'::jsonb, 'income_other', false, '73', 3610),
  ('FR', 'default', '74', 'Subventions d''exploitation', '{}'::jsonb, 'income_other', false, null, 3620),
  ('FR', 'default', '740', 'Subventions d''exploitation', '{}'::jsonb, 'income_other', false, '74', 3630),
  ('FR', 'default', '740000', 'Subventions d''exploitation', '{}'::jsonb, 'income_other', false, '740', 3640),
  ('FR', 'default', '75', 'Autres produits de gestion courante', '{}'::jsonb, 'income_other', false, null, 3650),
  ('FR', 'default', '751', 'Redevances pour concessions, brevets, licences et marques', '{}'::jsonb, 'income_other', false, '75', 3660),
  ('FR', 'default', '752', 'Revenus des immeubles non affectés aux activités professionnelles', '{}'::jsonb, 'income_other', false, '75', 3670),
  ('FR', 'default', '755', 'Quote-part de résultat sur opérations faites en commun', '{}'::jsonb, 'income_other', false, '75', 3680),
  ('FR', 'default', '758', 'Produits divers de gestion courante', '{}'::jsonb, 'income_other', false, '75', 3690),
  ('FR', 'default', '758000', 'Produits divers de gestion courante', '{}'::jsonb, 'income_other', false, '758', 3700),
  ('FR', 'default', '76', 'Produits financiers', '{}'::jsonb, 'income_other', false, null, 3710),
  ('FR', 'default', '761', 'Produits de participations', '{}'::jsonb, 'income_other', false, '76', 3720),
  ('FR', 'default', '762', 'Produits des autres immobilisations financières', '{}'::jsonb, 'income_other', false, '76', 3730),
  ('FR', 'default', '763', 'Revenus des autres créances', '{}'::jsonb, 'income_other', false, '76', 3740),
  ('FR', 'default', '764', 'Revenus des valeurs mobilières de placement', '{}'::jsonb, 'income_other', false, '76', 3750),
  ('FR', 'default', '765', 'Escomptes obtenus', '{}'::jsonb, 'income_other', false, '76', 3760),
  ('FR', 'default', '766', 'Gains de change', '{}'::jsonb, 'income_other', false, '76', 3770),
  ('FR', 'default', '766000', 'Gains de change', '{}'::jsonb, 'income_other', false, '766', 3780),
  ('FR', 'default', '768', 'Autres produits financiers', '{}'::jsonb, 'income_other', false, '76', 3790),
  ('FR', 'default', '77', 'Produits exceptionnels', '{}'::jsonb, 'income_other', false, null, 3800),
  ('FR', 'default', '771', 'Produits exceptionnels sur opérations de gestion', '{}'::jsonb, 'income_other', false, '77', 3810),
  ('FR', 'default', '775', 'Produits des cessions d''éléments d''actif', '{}'::jsonb, 'income_other', false, '77', 3820),
  ('FR', 'default', '775000', 'Produits des cessions d''éléments d''actif', '{}'::jsonb, 'income_other', false, '775', 3830),
  ('FR', 'default', '777', 'Quote-part des subventions d''investissement virée au résultat', '{}'::jsonb, 'income_other', false, '77', 3840),
  ('FR', 'default', '778', 'Autres produits exceptionnels', '{}'::jsonb, 'income_other', false, '77', 3850),
  ('FR', 'default', '78', 'Reprises sur amortissements, dépréciations et provisions', '{}'::jsonb, 'income_other', false, null, 3860),
  ('FR', 'default', '781', 'Reprises sur amortissements et provisions (exploitation)', '{}'::jsonb, 'income_other', false, '78', 3870),
  ('FR', 'default', '786', 'Reprises sur dépréciations et provisions (financières)', '{}'::jsonb, 'income_other', false, '78', 3880),
  ('FR', 'default', '79', 'Transferts de charges', '{}'::jsonb, 'income_other', false, null, 3890),
  ('FR', 'default', '791', 'Transferts de charges d''exploitation', '{}'::jsonb, 'income_other', false, '79', 3900),
  ('FR', 'default', '791000', 'Transferts de charges d''exploitation', '{}'::jsonb, 'income_other', false, '791', 3910),
  ('FR', 'default', '796', 'Transferts de charges financières', '{}'::jsonb, 'income_other', false, '79', 3920)
on conflict (country, chart_code, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, journal_type, sequence) values
  ('FR', 'BNK', 'Journal de banque', 'bank', 30),
  ('FR', 'CSH', 'Journal de caisse', 'cash', 40),
  ('FR', 'MISC', 'Opérations diverses', 'general', 50),
  ('FR', 'OPN', 'Journal des à-nouveaux', 'opening', 60),
  ('FR', 'PUR', 'Journal des achats', 'purchase', 20),
  ('FR', 'SAL', 'Journal des ventes', 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code)
values
  ('FR', 'FR-P-00', 'Achat exonere', 'Sans TVA', 'percent', 0, 'purchase', 'exempt', date '1993-01-01', null, 'CGI, art. 261', 'E', 'VATEX-EU-132', 150, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-055', 'Achat 5,5 %', 'Autres biens et services', 'percent', 5.5, 'purchase', 'domestic', date '2014-01-01', null, 'CGI, art. 278-0 bis', 'S', null, 140, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-10', 'Achat 10 %', 'Autres biens et services', 'percent', 10, 'purchase', 'domestic', date '2014-01-01', null, 'CGI, art. 278 bis', 'S', null, 130, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-20', 'Achat 20 %', 'Autres biens et services', 'percent', 20, 'purchase', 'domestic', date '2014-01-01', null, 'CGI, art. 278', 'S', null, 110, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-20-CARB', 'Carburant vehicule de tourisme 20 % — deduction 80 %', 'Essences et gazoles des vehicules exclus du droit a deduction. La TVA non deductible suit le compte de la ligne ; la CA3 ne porte aucune grille de base a l''entree.', 'percent', 20, 'purchase', 'domestic', date '2021-01-01', null, 'CGI, art. 298, 4, 1 a et b', 'S', null, 200, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-20-I', 'Achat immobilisation 20 %', 'Immobilisations', 'percent', 20, 'purchase', 'domestic', date '2014-01-01', null, 'CGI, art. 278', 'S', null, 120, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-AL-20', 'Achat autoliquidation 20 %', 'Assujetti non etabli, lignes 3C/08/20', 'percent', 20, 'purchase', 'domestic_reverse_charge', date '2014-01-01', null, 'CGI, art. 283-1', 'AE', 'VATEX-EU-AE', 180, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-ICG-20', 'Acquisition intracom. biens 20 %', 'Autoliquidation, lignes 03/08/20', 'percent', 20, 'purchase', 'intracom_acquisition_goods', date '1993-01-01', null, 'CGI, art. 256 bis', 'AE', 'VATEX-EU-AE', 160, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-ICS-20', 'Service intracom. recu 20 %', 'Autoliquidation, lignes 2A/08/20', 'percent', 20, 'purchase', 'intracom_acquisition_services', date '2010-01-01', null, 'CGI, art. 283-2', 'AE', 'VATEX-EU-AE', 170, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-IMP-20', 'Importation autoliquidee 20 %', 'Lignes 3A/08/20', 'percent', 20, 'purchase', 'import', date '2022-01-01', null, 'CGI, art. 293 A', 'S', null, 190, 'vat', true, null, false, false, null),
  ('FR', 'FR-S-021', 'Vente 2,1 %', 'Taux particulier', 'percent', 2.1, 'sale', 'domestic', date '2014-01-01', null, 'CGI, art. 281 quater', 'S', null, 40, 'vat', true, null, false, false, null),
  ('FR', 'FR-S-055', 'Vente 5,5 %', 'Taux reduit', 'percent', 5.5, 'sale', 'domestic', date '2014-01-01', null, 'CGI, art. 278-0 bis', 'S', null, 30, 'vat', true, null, false, false, null),
  ('FR', 'FR-S-10', 'Vente 10 %', 'Taux reduit', 'percent', 10, 'sale', 'domestic', date '2014-01-01', null, 'CGI, art. 278 bis', 'S', null, 20, 'vat', true, null, false, false, null),
  ('FR', 'FR-S-20', 'Vente 20 %', 'Taux normal', 'percent', 20, 'sale', 'domestic', date '2014-01-01', null, 'CGI, art. 278', 'S', null, 10, 'vat', true, null, false, false, null),
  ('FR', 'FR-S-AL', 'Vente autoliquidation', 'TVA due par le preneur', 'percent', 0, 'sale', 'domestic_reverse_charge', date '2014-01-01', null, 'CGI, art. 283-2 nonies', 'AE', 'VATEX-EU-AE', 50, 'vat', true, null, false, false, null),
  ('FR', 'FR-S-EXP', 'Exportation hors UE', 'Exoneree', 'percent', 0, 'sale', 'export', date '1993-01-01', null, 'CGI, art. 262 I', 'G', 'VATEX-EU-G', 80, 'vat', true, null, false, false, null),
  ('FR', 'FR-S-ICG', 'Livraison intracommunautaire', 'Biens, exoneree', 'percent', 0, 'sale', 'intracom_goods', date '1993-01-01', null, 'CGI, art. 262 ter I', 'K', 'VATEX-EU-IC', 60, 'vat', true, null, false, false, null),
  ('FR', 'FR-S-ICS', 'Service intracommunautaire', 'Autoliquidation par le preneur', 'percent', 0, 'sale', 'intracom_services', date '2010-01-01', null, 'CGI, art. 259-1', 'AE', 'VATEX-EU-AE', 70, 'vat', true, null, false, false, null)
on conflict (country, code) do update set
  name            = excluded.name,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('FR-P-055', 'invoice', 'tax', 100, '445660', '20', 100, 'FR-CA3', 20),
    ('FR-P-055', 'credit_note', 'tax', 100, '445660', '20', -100, 'FR-CA3', 20),
    ('FR-P-10', 'invoice', 'tax', 100, '445660', '20', 100, 'FR-CA3', 20),
    ('FR-P-10', 'credit_note', 'tax', 100, '445660', '20', -100, 'FR-CA3', 20),
    ('FR-P-20', 'invoice', 'tax', 100, '445660', '20', 100, 'FR-CA3', 20),
    ('FR-P-20', 'credit_note', 'tax', 100, '445660', '20', -100, 'FR-CA3', 20),
    ('FR-P-20-CARB', 'invoice', 'tax', 80, '445660', '20', 80, 'FR-CA3', 20),
    ('FR-P-20-CARB', 'invoice', 'tax_on_base', 20, null, null, 100, null, 30),
    ('FR-P-20-CARB', 'credit_note', 'tax', 80, '445660', '20', -80, 'FR-CA3', 20),
    ('FR-P-20-CARB', 'credit_note', 'tax_on_base', 20, null, null, 100, null, 30),
    ('FR-P-20-I', 'invoice', 'tax', 100, '445662', '19', 100, 'FR-CA3', 20),
    ('FR-P-20-I', 'credit_note', 'tax', 100, '445662', '19', -100, 'FR-CA3', 20),
    ('FR-P-AL-20', 'invoice', 'base', 100, null, '3C', 100, 'FR-CA3', 10),
    ('FR-P-AL-20', 'invoice', 'tax', 100, '445660', '20', 100, 'FR-CA3', 20),
    ('FR-P-AL-20', 'invoice', 'tax', -100, '445200', '08', 100, 'FR-CA3', 30),
    ('FR-P-AL-20', 'credit_note', 'base', 100, null, '3C', -100, 'FR-CA3', 10),
    ('FR-P-AL-20', 'credit_note', 'tax', 100, '445660', '20', -100, 'FR-CA3', 20),
    ('FR-P-AL-20', 'credit_note', 'tax', -100, '445200', '08', -100, 'FR-CA3', 30),
    ('FR-P-ICG-20', 'invoice', 'base', 100, null, '03', 100, 'FR-CA3', 10),
    ('FR-P-ICG-20', 'invoice', 'tax', 100, '445660', '20', 100, 'FR-CA3', 20),
    ('FR-P-ICG-20', 'invoice', 'tax', -100, '445200', '08', 100, 'FR-CA3', 30),
    ('FR-P-ICG-20', 'credit_note', 'base', 100, null, '03', -100, 'FR-CA3', 10),
    ('FR-P-ICG-20', 'credit_note', 'tax', 100, '445660', '20', -100, 'FR-CA3', 20),
    ('FR-P-ICG-20', 'credit_note', 'tax', -100, '445200', '08', -100, 'FR-CA3', 30),
    ('FR-P-ICS-20', 'invoice', 'base', 100, null, '2A', 100, 'FR-CA3', 10),
    ('FR-P-ICS-20', 'invoice', 'tax', 100, '445660', '20', 100, 'FR-CA3', 20),
    ('FR-P-ICS-20', 'invoice', 'tax', -100, '445200', '08', 100, 'FR-CA3', 30),
    ('FR-P-ICS-20', 'credit_note', 'base', 100, null, '2A', -100, 'FR-CA3', 10),
    ('FR-P-ICS-20', 'credit_note', 'tax', 100, '445660', '20', -100, 'FR-CA3', 20),
    ('FR-P-ICS-20', 'credit_note', 'tax', -100, '445200', '08', -100, 'FR-CA3', 30),
    ('FR-P-IMP-20', 'invoice', 'base', 100, null, '3A', 100, 'FR-CA3', 10),
    ('FR-P-IMP-20', 'invoice', 'tax', 100, '445660', '20', 100, 'FR-CA3', 20),
    ('FR-P-IMP-20', 'invoice', 'tax', -100, '445200', '08', 100, 'FR-CA3', 30),
    ('FR-P-IMP-20', 'credit_note', 'base', 100, null, '3A', -100, 'FR-CA3', 10),
    ('FR-P-IMP-20', 'credit_note', 'tax', 100, '445660', '20', -100, 'FR-CA3', 20),
    ('FR-P-IMP-20', 'credit_note', 'tax', -100, '445200', '08', -100, 'FR-CA3', 30),
    ('FR-S-021', 'invoice', 'base', 100, null, '13', 100, 'FR-CA3', 10),
    ('FR-S-021', 'invoice', 'tax', 100, '445710', '13', 100, 'FR-CA3', 20),
    ('FR-S-021', 'credit_note', 'base', 100, null, '13', -100, 'FR-CA3', 10),
    ('FR-S-021', 'credit_note', 'tax', 100, '445710', '13', -100, 'FR-CA3', 20),
    ('FR-S-055', 'invoice', 'base', 100, null, '09', 100, 'FR-CA3', 10),
    ('FR-S-055', 'invoice', 'tax', 100, '445710', '09', 100, 'FR-CA3', 20),
    ('FR-S-055', 'credit_note', 'base', 100, null, '09', -100, 'FR-CA3', 10),
    ('FR-S-055', 'credit_note', 'tax', 100, '445710', '09', -100, 'FR-CA3', 20),
    ('FR-S-10', 'invoice', 'base', 100, null, '9B', 100, 'FR-CA3', 10),
    ('FR-S-10', 'invoice', 'tax', 100, '445710', '9B', 100, 'FR-CA3', 20),
    ('FR-S-10', 'credit_note', 'base', 100, null, '9B', -100, 'FR-CA3', 10),
    ('FR-S-10', 'credit_note', 'tax', 100, '445710', '9B', -100, 'FR-CA3', 20),
    ('FR-S-20', 'invoice', 'base', 100, null, '08', 100, 'FR-CA3', 10),
    ('FR-S-20', 'invoice', 'tax', 100, '445710', '08', 100, 'FR-CA3', 20),
    ('FR-S-20', 'credit_note', 'base', 100, null, '08', -100, 'FR-CA3', 10),
    ('FR-S-20', 'credit_note', 'tax', 100, '445710', '08', -100, 'FR-CA3', 20),
    ('FR-S-AL', 'invoice', 'base', 100, null, '05', 100, 'FR-CA3', 10),
    ('FR-S-AL', 'credit_note', 'base', 100, null, '05', -100, 'FR-CA3', 10),
    ('FR-S-EXP', 'invoice', 'base', 100, null, '04', 100, 'FR-CA3', 10),
    ('FR-S-EXP', 'credit_note', 'base', 100, null, '04', -100, 'FR-CA3', 10),
    ('FR-S-ICG', 'invoice', 'base', 100, null, '06', 100, 'FR-CA3', 10),
    ('FR-S-ICG', 'credit_note', 'base', 100, null, '06', -100, 'FR-CA3', 10),
    ('FR-S-ICS', 'invoice', 'base', 100, null, '05', 100, 'FR-CA3', 10),
    ('FR-S-ICS', 'credit_note', 'base', 100, null, '05', -100, 'FR-CA3', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'FR' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, period, valid_from, valid_to, legal_reference, is_periodic_return)
values
  ('FR', 'FR-CA3', 'Déclaration de TVA 3310-CA3', 'month_or_quarter', date '2022-01-01', null, 'CGI, art. 287 — formulaire 3310-CA3', true)
on conflict (country, code) do update set
  name               = excluded.name,
  period             = excluded.period,
  valid_from         = excluded.valid_from,
  valid_to           = excluded.valid_to,
  legal_reference    = excluded.legal_reference,
  is_periodic_return = excluded.is_periodic_return;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence,
   plus_boxes, minus_boxes, floor_zero, hidden, xml_element, legal_reference)
values
  ('FR', 'FR-CA3', '01', 'total', 'Ventes, prestations de services', '{}'::jsonb, 10, array['08:base', '09:base', '9B:base', '13:base']::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '03', 'base', 'Acquisitions intracommunautaires', '{}'::jsonb, 20, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '2A', 'base', 'Achats de prestations de services intracommunautaires', '{}'::jsonb, 30, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '3A', 'base', 'Importations autoliquidées', '{}'::jsonb, 40, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '3C', 'base', 'Achats de biens ou de prestations auprès d''un assujetti non établi en France', '{}'::jsonb, 50, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '04', 'base', 'Exportations hors Union européenne', '{}'::jsonb, 60, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '05', 'base', 'Autres opérations non imposables', '{}'::jsonb, 70, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '06', 'base', 'Livraisons intracommunautaires', '{}'::jsonb, 80, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '08', 'base', 'Taux normal 20 % — base hors taxe', '{}'::jsonb, 100, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '09', 'base', 'Taux réduit 5,5 % — base hors taxe', '{}'::jsonb, 110, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '9B', 'base', 'Taux réduit 10 % — base hors taxe', '{}'::jsonb, 120, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '13', 'base', 'Taux particulier 2,1 % — base hors taxe', '{}'::jsonb, 130, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '08', 'tax', 'Taux normal 20 % — TVA due', '{}'::jsonb, 140, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '09', 'tax', 'Taux réduit 5,5 % — TVA due', '{}'::jsonb, 150, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '9B', 'tax', 'Taux réduit 10 % — TVA due', '{}'::jsonb, 160, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '13', 'tax', 'Taux particulier 2,1 % — TVA due', '{}'::jsonb, 170, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '16', 'total', 'Total de la TVA brute due', '{}'::jsonb, 200, array['08:tax', '09:tax', '9B:tax', '13:tax']::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '19', 'tax', 'TVA déductible sur immobilisations', '{}'::jsonb, 210, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '20', 'tax', 'TVA déductible sur autres biens et services', '{}'::jsonb, 220, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '23', 'total', 'Total de la TVA déductible', '{}'::jsonb, 230, array['19', '20']::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '28', 'total', 'TVA nette due', '{}'::jsonb, 240, array['16']::text[], array['23']::text[], true, false, null, null),
  ('FR', 'FR-CA3', '25', 'total', 'Crédit de TVA', '{}'::jsonb, 250, array['23']::text[], array['16']::text[], true, false, null, null)
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference;

insert into statement_templates
  (code, country, chart_code, name, kind, framework, valid_from, valid_to, legal_reference)
values
  ('FR-2050', 'FR', 'default', 'Bilan — liasse fiscale 2050 et 2051', 'balance_sheet', 'FR-PCG', date '1970-01-01', null, 'Formulaires 2050-SD et 2051-SD, millésime 2026 ; règlement ANC 2022-06'),
  ('FR-2052', 'FR', 'default', 'Compte de résultat — liasse fiscale 2052 et 2053', 'income_statement', 'FR-PCG', date '1970-01-01', null, 'Formulaires 2052-SD et 2053-SD, millésime 2026 ; règlement ANC 2022-06')
on conflict (code) do update set
  country         = excluded.country,
  chart_code      = excluded.chart_code,
  name            = excluded.name,
  kind            = excluded.kind,
  framework       = excluded.framework,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference;

insert into statement_line_templates
  (statement_code, code, parent_code, name, name_i18n, sequence, sign, is_total,
   plus_lines, minus_lines, xbrl_element, legal_reference)
values
  ('FR-2050', 'AA', 'CO', 'Capital souscrit non appelé (I)', '{}'::jsonb, 10, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'AB', 'BJ', 'Frais d''établissement', '{}'::jsonb, 20, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'CX', 'BJ', 'Frais de développement', '{}'::jsonb, 30, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'AF', 'BJ', 'Concessions, brevets et droits similaires', '{}'::jsonb, 40, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'AH', 'BJ', 'Fonds commercial', '{}'::jsonb, 50, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'AJ', 'BJ', 'Autres immobilisations incorporelles', '{}'::jsonb, 60, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'AL', 'BJ', 'Immobilisations incorporelles en cours, avances et acomptes', '{}'::jsonb, 70, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'AN', 'BJ', 'Terrains', '{}'::jsonb, 80, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'AP', 'BJ', 'Constructions', '{}'::jsonb, 90, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'AR', 'BJ', 'Installations techniques, matériel et outillage industriels', '{}'::jsonb, 100, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'AT', 'BJ', 'Autres immobilisations corporelles', '{}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'AV', 'BJ', 'Immobilisations corporelles en cours, avances et acomptes', '{}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'CS', 'BJ', 'Participations', '{}'::jsonb, 130, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'CU', 'BJ', 'Titres immobilisés de l''activité de portefeuille', '{}'::jsonb, 140, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'BB', 'BJ', 'Créances rattachées à des participations', '{}'::jsonb, 150, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'BD', 'BJ', 'Autres titres immobilisés', '{}'::jsonb, 160, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'BF', 'BJ', 'Prêts', '{}'::jsonb, 170, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'BH', 'BJ', 'Autres immobilisations financières', '{}'::jsonb, 180, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'BJ', 'CO', 'TOTAL (II) — Actif immobilisé', '{}'::jsonb, 190, 1, true, array['AB', 'CX', 'AF', 'AH', 'AJ', 'AL', 'AN', 'AP', 'AR', 'AT', 'AV', 'CS', 'CU', 'BB', 'BD', 'BF', 'BH']::text[], '{}'::text[], null, null),
  ('FR-2050', 'BL', 'CJ', 'Matières premières, approvisionnements', '{}'::jsonb, 200, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'BN', 'CJ', 'En-cours de production de biens', '{}'::jsonb, 210, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'BP', 'CJ', 'En-cours de production de services', '{}'::jsonb, 220, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'BR', 'CJ', 'Produits intermédiaires et finis', '{}'::jsonb, 230, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'BT', 'CJ', 'Marchandises', '{}'::jsonb, 240, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'BV', 'CJ', 'Avances et acomptes versés sur commandes', '{}'::jsonb, 250, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'BX', 'CJ', 'Clients et comptes rattachés', '{}'::jsonb, 260, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'BZ', 'CJ', 'Autres créances', '{}'::jsonb, 270, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'CB', 'CJ', 'Capital souscrit et appelé, non versé', '{}'::jsonb, 280, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'CD', 'CJ', 'Valeurs mobilières de placement', '{}'::jsonb, 290, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'CF', 'CJ', 'Disponibilités', '{}'::jsonb, 300, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'CH', 'CJ', 'Charges constatées d''avance', '{}'::jsonb, 310, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'CJ', 'CO', 'TOTAL (III) — Actif circulant', '{}'::jsonb, 320, 1, true, array['BL', 'BN', 'BP', 'BR', 'BT', 'BV', 'BX', 'BZ', 'CB', 'CD', 'CF', 'CH']::text[], '{}'::text[], null, null),
  ('FR-2050', 'CO', null, 'TOTAL GÉNÉRAL DE L''ACTIF', '{}'::jsonb, 330, 1, true, array['AA', 'BJ', 'CJ']::text[], '{}'::text[], null, null),
  ('FR-2050', 'DA', 'DL', 'Capital social ou individuel', '{}'::jsonb, 340, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DB', 'DL', 'Primes d''émission, de fusion, d''apport', '{}'::jsonb, 350, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DC', 'DL', 'Écarts de réévaluation', '{}'::jsonb, 360, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DD', 'DL', 'Réserve légale', '{}'::jsonb, 370, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DE', 'DL', 'Réserves statutaires ou contractuelles', '{}'::jsonb, 380, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DF', 'DL', 'Réserves réglementées', '{}'::jsonb, 390, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DG', 'DL', 'Autres réserves', '{}'::jsonb, 400, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DH', 'DL', 'Report à nouveau', '{}'::jsonb, 410, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DI', 'DL', 'RÉSULTAT DE L''EXERCICE', '{}'::jsonb, 420, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DJ', 'DL', 'Subventions d''investissement', '{}'::jsonb, 430, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DK', 'DL', 'Provisions réglementées', '{}'::jsonb, 440, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DL', 'EE', 'TOTAL (I) — Capitaux propres', '{}'::jsonb, 450, 1, true, array['DA', 'DB', 'DC', 'DD', 'DE', 'DF', 'DG', 'DH', 'DI', 'DJ', 'DK']::text[], '{}'::text[], null, null),
  ('FR-2050', 'DM', 'DO', 'Produit des émissions de titres participatifs', '{}'::jsonb, 460, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DN', 'DO', 'Avances conditionnées', '{}'::jsonb, 470, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DO', 'EE', 'TOTAL (II) — Autres fonds propres', '{}'::jsonb, 480, 1, true, array['DM', 'DN']::text[], '{}'::text[], null, null),
  ('FR-2050', 'DP', 'DR', 'Provisions pour risques', '{}'::jsonb, 490, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DQ', 'DR', 'Provisions pour charges', '{}'::jsonb, 500, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DR', 'EE', 'TOTAL (III) — Provisions', '{}'::jsonb, 510, 1, true, array['DP', 'DQ']::text[], '{}'::text[], null, null),
  ('FR-2050', 'DS', 'EC', 'Emprunts obligataires convertibles', '{}'::jsonb, 520, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DT', 'EC', 'Autres emprunts obligataires', '{}'::jsonb, 530, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DU', 'EC', 'Emprunts et dettes auprès des établissements de crédit', '{}'::jsonb, 540, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DV', 'EC', 'Emprunts et dettes financières divers', '{}'::jsonb, 550, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DW', 'EC', 'Avances et acomptes reçus sur commandes en cours', '{}'::jsonb, 560, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DX', 'EC', 'Dettes fournisseurs et comptes rattachés', '{}'::jsonb, 570, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DY', 'EC', 'Dettes fiscales et sociales', '{}'::jsonb, 580, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'DZ', 'EC', 'Dettes sur immobilisations et comptes rattachés', '{}'::jsonb, 590, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'EA', 'EC', 'Autres dettes', '{}'::jsonb, 600, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'EB', 'EC', 'Produits constatés d''avance', '{}'::jsonb, 610, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2050', 'EC', 'EE', 'TOTAL (IV) — Dettes', '{}'::jsonb, 620, 1, true, array['DS', 'DT', 'DU', 'DV', 'DW', 'DX', 'DY', 'DZ', 'EA', 'EB']::text[], '{}'::text[], null, null),
  ('FR-2050', 'EE', null, 'TOTAL GÉNÉRAL DU PASSIF', '{}'::jsonb, 630, 1, true, array['DL', 'DO', 'DR', 'EC']::text[], '{}'::text[], null, null),
  ('FR-2052', 'FA', 'FJ', 'Ventes de marchandises', '{}'::jsonb, 10, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'FD', 'FJ', 'Production vendue — biens', '{}'::jsonb, 20, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'FG', 'FJ', 'Production vendue — services et opérations à long terme', '{}'::jsonb, 30, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'FJ', 'FR', 'CHIFFRES D''AFFAIRES NETS', '{}'::jsonb, 40, 1, true, array['FA', 'FD', 'FG']::text[], '{}'::text[], null, null),
  ('FR-2052', 'FM', 'FR', 'Production stockée', '{}'::jsonb, 50, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'FN', 'FR', 'Production immobilisée', '{}'::jsonb, 60, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'FO', 'FR', 'Subventions d''exploitation', '{}'::jsonb, 70, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'FP', 'FR', 'Reprises sur amortissements, dépréciations et provisions, transferts de charges', '{}'::jsonb, 80, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'FQ', 'FR', 'Autres produits', '{}'::jsonb, 90, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'FR', null, 'TOTAL DES PRODUITS D''EXPLOITATION (I)', '{}'::jsonb, 100, 1, true, array['FJ', 'FM', 'FN', 'FO', 'FP', 'FQ']::text[], '{}'::text[], null, null),
  ('FR-2052', 'FS', 'GF', 'Achats de marchandises', '{}'::jsonb, 110, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'FT', 'GF', 'Variation de stocks (marchandises)', '{}'::jsonb, 120, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'FU', 'GF', 'Achats de matières premières et autres approvisionnements', '{}'::jsonb, 130, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'FV', 'GF', 'Variation de stocks (matières premières et approvisionnements)', '{}'::jsonb, 140, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'FW', 'GF', 'Autres achats et charges externes', '{}'::jsonb, 150, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'FX', 'GF', 'Impôts, taxes et versements assimilés', '{}'::jsonb, 160, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'FY', 'GF', 'Salaires et traitements', '{}'::jsonb, 170, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'FZ', 'GF', 'Cotisations sociales', '{}'::jsonb, 180, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GA', 'GF', 'Dotations aux amortissements sur immobilisations', '{}'::jsonb, 190, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GB', 'GF', 'Dotations aux dépréciations sur immobilisations', '{}'::jsonb, 200, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GC', 'GF', 'Sur actif circulant : dotations aux dépréciations', '{}'::jsonb, 210, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GD', 'GF', 'Pour risques et charges : dotations aux provisions', '{}'::jsonb, 220, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GE', 'GF', 'Autres charges', '{}'::jsonb, 230, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GF', null, 'TOTAL DES CHARGES D''EXPLOITATION (II)', '{}'::jsonb, 240, 1, true, array['FS', 'FT', 'FU', 'FV', 'FW', 'FX', 'FY', 'FZ', 'GA', 'GB', 'GC', 'GD', 'GE']::text[], '{}'::text[], null, null),
  ('FR-2052', 'GG', null, '1 — RÉSULTAT D''EXPLOITATION (I − II)', '{}'::jsonb, 250, 1, true, array['FR']::text[], array['GF']::text[], null, null),
  ('FR-2052', 'GH', null, 'Bénéfice attribué ou perte transférée (III)', '{}'::jsonb, 260, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GI', null, 'Perte supportée ou bénéfice transféré (IV)', '{}'::jsonb, 270, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GJ', 'GP', 'Produits financiers de participations', '{}'::jsonb, 280, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GK', 'GP', 'Produits des autres valeurs mobilières et créances de l''actif immobilisé', '{}'::jsonb, 290, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GL', 'GP', 'Autres intérêts et produits assimilés', '{}'::jsonb, 300, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GM', 'GP', 'Reprises sur dépréciations et transferts de charges financières', '{}'::jsonb, 310, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GN', 'GP', 'Différences positives de change', '{}'::jsonb, 320, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GO', 'GP', 'Produits nets sur cessions de valeurs mobilières de placement', '{}'::jsonb, 330, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GP', null, 'TOTAL DES PRODUITS FINANCIERS (V)', '{}'::jsonb, 340, 1, true, array['GJ', 'GK', 'GL', 'GM', 'GN', 'GO']::text[], '{}'::text[], null, null),
  ('FR-2052', 'GQ', 'GU', 'Dotations financières aux amortissements, dépréciations et provisions', '{}'::jsonb, 350, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GR', 'GU', 'Intérêts et charges assimilées', '{}'::jsonb, 360, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GS', 'GU', 'Différences négatives de change', '{}'::jsonb, 370, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GT', 'GU', 'Charges nettes sur cessions de valeurs mobilières de placement', '{}'::jsonb, 380, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'GU', null, 'TOTAL DES CHARGES FINANCIÈRES (VI)', '{}'::jsonb, 390, 1, true, array['GQ', 'GR', 'GS', 'GT']::text[], '{}'::text[], null, null),
  ('FR-2052', 'GV', null, '2 — RÉSULTAT FINANCIER (V − VI)', '{}'::jsonb, 400, 1, true, array['GP']::text[], array['GU']::text[], null, null),
  ('FR-2052', 'GW', null, '3 — RÉSULTAT COURANT AVANT IMPÔTS', '{}'::jsonb, 410, 1, true, array['GG', 'GH', 'GP']::text[], array['GI', 'GU']::text[], null, null),
  ('FR-2052', 'HD', null, 'Produits exceptionnels (VII)', '{}'::jsonb, 420, -1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'HH', null, 'Charges exceptionnelles (VIII)', '{}'::jsonb, 430, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'HI', null, '4 — RÉSULTAT EXCEPTIONNEL (VII − VIII)', '{}'::jsonb, 440, 1, true, array['HD']::text[], array['HH']::text[], null, null),
  ('FR-2052', 'HJ', null, 'Participation des salariés aux résultats (IX)', '{}'::jsonb, 450, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'HK', null, 'Impôts sur les bénéfices (X)', '{}'::jsonb, 460, 1, false, '{}'::text[], '{}'::text[], null, null),
  ('FR-2052', 'HL', null, 'TOTAL DES PRODUITS (I + III + V + VII)', '{}'::jsonb, 470, 1, true, array['FR', 'GH', 'GP', 'HD']::text[], '{}'::text[], null, null),
  ('FR-2052', 'HM', null, 'TOTAL DES CHARGES (II + IV + VI + VIII + IX + X)', '{}'::jsonb, 480, 1, true, array['GF', 'GI', 'GU', 'HH', 'HJ', 'HK']::text[], '{}'::text[], null, null),
  ('FR-2052', 'HN', null, '5 — BÉNÉFICE OU PERTE', '{}'::jsonb, 490, 1, true, array['HL']::text[], array['HM']::text[], null, null)
on conflict (statement_code, code) do update set
  parent_code     = excluded.parent_code,
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  sign            = excluded.sign,
  is_total        = excluded.is_total,
  plus_lines      = excluded.plus_lines,
  minus_lines     = excluded.minus_lines,
  xbrl_element    = excluded.xbrl_element,
  legal_reference = excluded.legal_reference;

insert into statement_line_rules
  (statement_code, line_code, sequence, rule_kind, code_from, code_to,
   account_type, balance_side)
select v.statement_code, v.line_code, v.sequence, v.rule_kind, v.code_from,
       v.code_to, v.account_type::account_type, v.balance_side
  from (values
    ('FR-2050', 'AA', 10, 'code_range', '109', '109', null, 'any'),
    ('FR-2050', 'AB', 10, 'code_range', '201', '201', null, 'any'),
    ('FR-2050', 'AB', 20, 'code_range', '2801', '2801', null, 'any'),
    ('FR-2050', 'CX', 10, 'code_range', '203', '203', null, 'any'),
    ('FR-2050', 'CX', 20, 'code_range', '2803', '2803', null, 'any'),
    ('FR-2050', 'AF', 10, 'code_range', '205', '205', null, 'any'),
    ('FR-2050', 'AF', 20, 'code_range', '2805', '2805', null, 'any'),
    ('FR-2050', 'AF', 30, 'code_range', '2905', '2905', null, 'any'),
    ('FR-2050', 'AH', 10, 'code_range', '206', '207', null, 'any'),
    ('FR-2050', 'AH', 20, 'code_range', '2807', '2807', null, 'any'),
    ('FR-2050', 'AH', 30, 'code_range', '2906', '2907', null, 'any'),
    ('FR-2050', 'AJ', 10, 'code_range', '208', '208', null, 'any'),
    ('FR-2050', 'AJ', 20, 'code_range', '2808', '2808', null, 'any'),
    ('FR-2050', 'AJ', 30, 'code_range', '290', '290', null, 'any'),
    ('FR-2050', 'AJ', 40, 'code_range', '2908', '2908', null, 'any'),
    ('FR-2050', 'AL', 10, 'code_range', '232', '232', null, 'any'),
    ('FR-2050', 'AL', 20, 'code_range', '237', '237', null, 'any'),
    ('FR-2050', 'AN', 10, 'code_range', '211', '212', null, 'any'),
    ('FR-2050', 'AN', 20, 'code_range', '2811', '2812', null, 'any'),
    ('FR-2050', 'AN', 30, 'code_range', '2911', '2911', null, 'any'),
    ('FR-2050', 'AP', 10, 'code_range', '213', '214', null, 'any'),
    ('FR-2050', 'AP', 20, 'code_range', '2813', '2814', null, 'any'),
    ('FR-2050', 'AR', 10, 'code_range', '215', '215', null, 'any'),
    ('FR-2050', 'AR', 20, 'code_range', '2815', '2815', null, 'any'),
    ('FR-2050', 'AT', 10, 'code_range', '218', '218', null, 'any'),
    ('FR-2050', 'AT', 20, 'code_range', '22', '22', null, 'any'),
    ('FR-2050', 'AT', 30, 'code_range', '2818', '2818', null, 'any'),
    ('FR-2050', 'AT', 40, 'code_range', '291', '291', null, 'any'),
    ('FR-2050', 'AV', 10, 'code_range', '231', '231', null, 'any'),
    ('FR-2050', 'AV', 20, 'code_range', '238', '238', null, 'any'),
    ('FR-2050', 'CS', 10, 'code_range', '261', '261', null, 'any'),
    ('FR-2050', 'CS', 20, 'code_range', '266', '266', null, 'any'),
    ('FR-2050', 'CS', 30, 'code_range', '2961', '2961', null, 'any'),
    ('FR-2050', 'CS', 40, 'code_range', '2966', '2966', null, 'any'),
    ('FR-2050', 'CU', 10, 'code_range', '273', '273', null, 'any'),
    ('FR-2050', 'CU', 20, 'code_range', '2973', '2973', null, 'any'),
    ('FR-2050', 'BB', 10, 'code_range', '267', '268', null, 'any'),
    ('FR-2050', 'BB', 20, 'code_range', '2967', '2968', null, 'any'),
    ('FR-2050', 'BD', 10, 'code_range', '271', '272', null, 'any'),
    ('FR-2050', 'BD', 20, 'code_range', '2971', '2972', null, 'any'),
    ('FR-2050', 'BF', 10, 'code_range', '274', '274', null, 'any'),
    ('FR-2050', 'BF', 20, 'code_range', '2974', '2974', null, 'any'),
    ('FR-2050', 'BH', 10, 'code_range', '275', '276', null, 'any'),
    ('FR-2050', 'BH', 20, 'code_range', '2975', '2976', null, 'any'),
    ('FR-2050', 'BL', 10, 'code_range', '31', '32', null, 'any'),
    ('FR-2050', 'BL', 20, 'code_range', '391', '392', null, 'any'),
    ('FR-2050', 'BN', 10, 'code_range', '33', '33', null, 'any'),
    ('FR-2050', 'BN', 20, 'code_range', '393', '393', null, 'any'),
    ('FR-2050', 'BP', 10, 'code_range', '34', '34', null, 'any'),
    ('FR-2050', 'BP', 20, 'code_range', '394', '394', null, 'any'),
    ('FR-2050', 'BR', 10, 'code_range', '35', '36', null, 'any'),
    ('FR-2050', 'BR', 20, 'code_range', '395', '396', null, 'any'),
    ('FR-2050', 'BT', 10, 'code_range', '37', '38', null, 'any'),
    ('FR-2050', 'BT', 20, 'code_range', '397', '398', null, 'any'),
    ('FR-2050', 'BV', 10, 'code_range', '4091', '4091', null, 'any'),
    ('FR-2050', 'BX', 10, 'code_range', '411', '411', null, 'any'),
    ('FR-2050', 'BX', 20, 'code_range', '413', '413', null, 'any'),
    ('FR-2050', 'BX', 30, 'code_range', '416', '418', null, 'any'),
    ('FR-2050', 'BX', 40, 'code_range', '491', '491', null, 'any'),
    ('FR-2050', 'BZ', 10, 'code_range', '42', '44', null, 'debit'),
    ('FR-2050', 'BZ', 20, 'code_range', '45', '47', null, 'debit'),
    ('FR-2050', 'BZ', 30, 'code_range', '4096', '4098', null, 'any'),
    ('FR-2050', 'CB', 10, 'code_range', '4562', '4562', null, 'any'),
    ('FR-2050', 'CD', 10, 'code_range', '50', '50', null, 'any'),
    ('FR-2050', 'CD', 20, 'code_range', '590', '590', null, 'any'),
    ('FR-2050', 'CF', 10, 'code_range', '51', '51', null, 'debit'),
    ('FR-2050', 'CF', 20, 'code_range', '52', '58', null, 'any'),
    ('FR-2050', 'CH', 10, 'code_range', '486', '486', null, 'any'),
    ('FR-2050', 'DA', 10, 'code_range', '101', '101', null, 'any'),
    ('FR-2050', 'DA', 20, 'code_range', '108', '108', null, 'any'),
    ('FR-2050', 'DB', 10, 'code_range', '104', '104', null, 'any'),
    ('FR-2050', 'DC', 10, 'code_range', '105', '105', null, 'any'),
    ('FR-2050', 'DC', 20, 'code_range', '107', '107', null, 'any'),
    ('FR-2050', 'DD', 10, 'code_range', '1061', '1061', null, 'any'),
    ('FR-2050', 'DE', 10, 'code_range', '1063', '1063', null, 'any'),
    ('FR-2050', 'DF', 10, 'code_range', '1062', '1062', null, 'any'),
    ('FR-2050', 'DF', 20, 'code_range', '1064', '1065', null, 'any'),
    ('FR-2050', 'DG', 10, 'code_range', '1066', '1069', null, 'any'),
    ('FR-2050', 'DH', 10, 'code_range', '11', '11', null, 'any'),
    ('FR-2050', 'DI', 10, 'code_range', '12', '12', null, 'any'),
    ('FR-2050', 'DJ', 10, 'code_range', '13', '13', null, 'any'),
    ('FR-2050', 'DK', 10, 'code_range', '14', '14', null, 'any'),
    ('FR-2050', 'DM', 10, 'code_range', '1671', '1671', null, 'any'),
    ('FR-2050', 'DN', 10, 'code_range', '1674', '1674', null, 'any'),
    ('FR-2050', 'DP', 10, 'code_range', '151', '151', null, 'any'),
    ('FR-2050', 'DQ', 10, 'code_range', '152', '159', null, 'any'),
    ('FR-2050', 'DS', 10, 'code_range', '161', '162', null, 'any'),
    ('FR-2050', 'DT', 10, 'code_range', '163', '163', null, 'any'),
    ('FR-2050', 'DU', 10, 'code_range', '164', '164', null, 'any'),
    ('FR-2050', 'DU', 20, 'code_range', '51', '51', null, 'credit'),
    ('FR-2050', 'DV', 10, 'code_range', '165', '168', null, 'any'),
    ('FR-2050', 'DV', 20, 'code_range', '17', '18', null, 'any'),
    ('FR-2050', 'DW', 10, 'code_range', '4191', '4191', null, 'any'),
    ('FR-2050', 'DX', 10, 'code_range', '401', '401', null, 'any'),
    ('FR-2050', 'DX', 20, 'code_range', '403', '403', null, 'any'),
    ('FR-2050', 'DX', 30, 'code_range', '408', '408', null, 'any'),
    ('FR-2050', 'DY', 10, 'code_range', '42', '44', null, 'credit'),
    ('FR-2050', 'DZ', 10, 'code_range', '404', '405', null, 'any'),
    ('FR-2050', 'EA', 10, 'code_range', '45', '47', null, 'credit'),
    ('FR-2050', 'EB', 10, 'code_range', '487', '487', null, 'any'),
    ('FR-2052', 'FA', 10, 'code_range', '707', '707', null, 'any'),
    ('FR-2052', 'FD', 10, 'code_range', '701', '703', null, 'any'),
    ('FR-2052', 'FG', 10, 'code_range', '704', '706', null, 'any'),
    ('FR-2052', 'FG', 20, 'code_range', '708', '709', null, 'any'),
    ('FR-2052', 'FG', 30, 'code_range', '73', '73', null, 'any'),
    ('FR-2052', 'FM', 10, 'code_range', '713', '713', null, 'any'),
    ('FR-2052', 'FN', 10, 'code_range', '72', '72', null, 'any'),
    ('FR-2052', 'FO', 10, 'code_range', '74', '74', null, 'any'),
    ('FR-2052', 'FP', 10, 'code_range', '781', '781', null, 'any'),
    ('FR-2052', 'FP', 20, 'code_range', '791', '791', null, 'any'),
    ('FR-2052', 'FQ', 10, 'code_range', '750', '754', null, 'any'),
    ('FR-2052', 'FQ', 20, 'code_range', '756', '759', null, 'any'),
    ('FR-2052', 'FS', 10, 'code_range', '607', '607', null, 'any'),
    ('FR-2052', 'FT', 10, 'code_range', '6037', '6037', null, 'any'),
    ('FR-2052', 'FU', 10, 'code_range', '601', '602', null, 'any'),
    ('FR-2052', 'FU', 20, 'code_range', '608', '609', null, 'any'),
    ('FR-2052', 'FV', 10, 'code_range', '6031', '6036', null, 'any'),
    ('FR-2052', 'FW', 10, 'code_range', '604', '606', null, 'any'),
    ('FR-2052', 'FW', 20, 'code_range', '61', '62', null, 'any'),
    ('FR-2052', 'FX', 10, 'code_range', '63', '63', null, 'any'),
    ('FR-2052', 'FY', 10, 'code_range', '641', '641', null, 'any'),
    ('FR-2052', 'FY', 20, 'code_range', '644', '644', null, 'any'),
    ('FR-2052', 'FZ', 10, 'code_range', '645', '649', null, 'any'),
    ('FR-2052', 'FZ', 20, 'code_range', '642', '643', null, 'any'),
    ('FR-2052', 'GA', 10, 'code_range', '6811', '6812', null, 'any'),
    ('FR-2052', 'GB', 10, 'code_range', '6816', '6816', null, 'any'),
    ('FR-2052', 'GC', 10, 'code_range', '6817', '6817', null, 'any'),
    ('FR-2052', 'GD', 10, 'code_range', '6815', '6815', null, 'any'),
    ('FR-2052', 'GD', 20, 'code_range', '6813', '6814', null, 'any'),
    ('FR-2052', 'GE', 10, 'code_range', '650', '654', null, 'any'),
    ('FR-2052', 'GE', 20, 'code_range', '656', '659', null, 'any'),
    ('FR-2052', 'GH', 10, 'code_range', '755', '755', null, 'any'),
    ('FR-2052', 'GI', 10, 'code_range', '655', '655', null, 'any'),
    ('FR-2052', 'GJ', 10, 'code_range', '761', '761', null, 'any'),
    ('FR-2052', 'GK', 10, 'code_range', '762', '762', null, 'any'),
    ('FR-2052', 'GL', 10, 'code_range', '763', '765', null, 'any'),
    ('FR-2052', 'GL', 20, 'code_range', '768', '769', null, 'any'),
    ('FR-2052', 'GM', 10, 'code_range', '786', '786', null, 'any'),
    ('FR-2052', 'GM', 20, 'code_range', '796', '796', null, 'any'),
    ('FR-2052', 'GN', 10, 'code_range', '766', '766', null, 'any'),
    ('FR-2052', 'GO', 10, 'code_range', '767', '767', null, 'any'),
    ('FR-2052', 'GQ', 10, 'code_range', '686', '686', null, 'any'),
    ('FR-2052', 'GR', 10, 'code_range', '661', '665', null, 'any'),
    ('FR-2052', 'GR', 20, 'code_range', '668', '669', null, 'any'),
    ('FR-2052', 'GS', 10, 'code_range', '666', '666', null, 'any'),
    ('FR-2052', 'GT', 10, 'code_range', '667', '667', null, 'any'),
    ('FR-2052', 'HD', 10, 'code_range', '77', '77', null, 'any'),
    ('FR-2052', 'HH', 10, 'code_range', '67', '67', null, 'any'),
    ('FR-2052', 'HH', 20, 'code_range', '687', '687', null, 'any'),
    ('FR-2052', 'HJ', 10, 'code_range', '691', '694', null, 'any'),
    ('FR-2052', 'HK', 10, 'code_range', '695', '699', null, 'any')
  ) as v (statement_code, line_code, sequence, rule_kind, code_from, code_to,
          account_type, balance_side)
on conflict (statement_code, line_code, sequence) do update set
  rule_kind    = excluded.rule_kind,
  code_from    = excluded.code_from,
  code_to      = excluded.code_to,
  account_type = excluded.account_type,
  balance_side = excluded.balance_side;

insert into country_defaults
  (country, name, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit)
values
  ('FR', 'France', 'EUR', '411000', '401000', '471000', '658000', '110000', '706000', '606300', '512000', '530000', 'SAL', 'PUR', 'MISC', 'fr', 'result_accounts', '120000', '129000', '119000', 'OPN', 'half_up', default)
on conflict (country) do update set
  name                   = excluded.name,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit;

update country_defaults set
  numbering_gapless       = true,
  number_format           = '{CODE}/{YYYY}/{NNNN}',
  legal_payment_days      = 30,
  late_payment_reference  = 'Code de commerce, art. L441-10, II — taux appliqué par la Banque centrale européenne à son opération de refinancement la plus récente majoré de dix points, sans pouvoir être inférieur à trois fois le taux d''intérêt légal ; art. D441-5 — indemnité forfaitaire de 40 € pour frais de recouvrement',
  tax_point_rule          = 'delivery_date',
  einvoice_profile        = 'factur-x-en16931',
  einvoice_mandatory_from = date '2026-09-01',
  party_scheme            = '0009',
  vat_scheme              = '9957',
  bank_statement_formats  = array['camt.053', 'cfonb120']::text[],
  payment_formats         = array['pain.001', 'cfonb160']::text[],
  fiscal_year_default     = 'calendar'
 where country = 'FR';

insert into legal_mention_templates
  (country, code, applies_when, text, text_i18n, sequence, valid_from, valid_to, legal_reference)
values
  ('FR', 'reverse_charge', 'reverse_charge', 'Autoliquidation — TVA due par le preneur.', '{"en":"Reverse charge — VAT to be accounted for by the customer."}'::jsonb, 10, date '1970-01-01', null, 'Code général des impôts, art. 283'),
  ('FR', 'intracom_goods', 'intra_eu_goods', 'Exonération de TVA — livraison intracommunautaire.', '{"en":"Exempt intra-Community supply."}'::jsonb, 20, date '1970-01-01', null, 'Code général des impôts, art. 262 ter, I'),
  ('FR', 'intracom_services', 'intra_eu_services', 'Autoliquidation — TVA due par le preneur.', '{"en":"Reverse charge — VAT due by the customer."}'::jsonb, 30, date '1970-01-01', null, 'Code général des impôts, art. 283-2 ; directive 2006/112/CE, art. 44 et 196'),
  ('FR', 'export', 'export', 'Exonération de TVA — exportation hors de l''Union européenne.', '{"en":"Exempt export outside the European Union."}'::jsonb, 40, date '1970-01-01', null, 'Code général des impôts, art. 262, I'),
  ('FR', 'small_business', 'small_business', 'TVA non applicable, art. 293 B du CGI.', '{"en":"VAT not applicable, article 293 B of the French tax code."}'::jsonb, 50, date '1970-01-01', null, 'Code général des impôts, art. 293 B'),
  ('FR', 'late_payment', 'late_payment', 'En cas de retard de paiement, des pénalités sont exigibles sans qu''un rappel soit nécessaire, ainsi qu''une indemnité forfaitaire de 40 € pour frais de recouvrement.', '{"en":"Late payment gives rise to interest without any reminder being necessary, together with a fixed recovery indemnity of 40 €."}'::jsonb, 60, date '1970-01-01', null, 'Code de commerce, art. L441-10 et D441-5')
on conflict (country, code) do update set
  applies_when    = excluded.applies_when,
  text            = excluded.text,
  text_i18n       = excluded.text_i18n,
  sequence        = excluded.sequence,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference;
