-- Ekwo OS — France: chart of accounts, journals, taxes and defaults.
--
-- Generated from packs/fr at version 1.1.0, do not edit.
-- Change the pack and run `ekwo pack build fr`; `ekwo pack check --all`
-- refuses a seed that is not the exact output of its pack, and the CI runs it.
--
-- Maintained by Ekwo — not yet reviewed by an accountant.
-- Written from:
--   Règlement ANC 2022-06 — plan comptable général
--   Code général des impôts, art. 278, 278 bis, 278-0 bis, 281 quater
--   Formulaire 3310-CA3
--   Code general des impots, art. 298, 4 — produits petroliers
--
-- In the pack, not compiled by this release:
--   documents — country_defaults columns and legal_mention_templates (P0-7)
--
-- Reference data: `install_country_template()` copies it into a company,
-- nothing here belongs to a company.

insert into country_packs
  (country, name, version, released_at, schema_min, certification_status,
   certified_by, certified_at, checksum)
values
  ('FR', 'France', '1.1.0', date '2026-09-12', '20260912091918', 'maintained', null, null, 'bdac03590a84389a1a0d74b3d956f9bbc411656c476d0feba41b6d74aeedcb57')
on conflict (country) do update set
  name                 = excluded.name,
  version              = excluded.version,
  released_at          = excluded.released_at,
  schema_min           = excluded.schema_min,
  certification_status = excluded.certification_status,
  certified_by         = excluded.certified_by,
  certified_at         = excluded.certified_at,
  checksum             = excluded.checksum;

insert into account_templates
  (country, code, name, name_i18n, account_type, reconcilable, parent_code, sequence)
values
  ('FR', '10', 'Capital et réserves', '{}'::jsonb, 'equity', false, null, 10),
  ('FR', '101', 'Capital', '{}'::jsonb, 'equity', false, '10', 20),
  ('FR', '101000', 'Capital', '{}'::jsonb, 'equity', false, '101', 30),
  ('FR', '104', 'Primes liées au capital social', '{}'::jsonb, 'equity', false, '10', 40),
  ('FR', '104100', 'Primes d''émission', '{}'::jsonb, 'equity', false, '104', 50),
  ('FR', '105', 'Écarts de réévaluation', '{}'::jsonb, 'equity', false, '10', 60),
  ('FR', '106', 'Réserves', '{}'::jsonb, 'equity', false, '10', 70),
  ('FR', '106100', 'Réserve légale', '{}'::jsonb, 'equity', false, '106', 80),
  ('FR', '106300', 'Réserves statutaires ou contractuelles', '{}'::jsonb, 'equity', false, '106', 90),
  ('FR', '108', 'Compte de l''exploitant', '{}'::jsonb, 'equity', false, '10', 100),
  ('FR', '11', 'Report à nouveau', '{}'::jsonb, 'equity_retained', false, null, 110),
  ('FR', '110', 'Report à nouveau (solde créditeur)', '{}'::jsonb, 'equity_retained', false, '11', 120),
  ('FR', '110000', 'Report à nouveau créditeur', '{}'::jsonb, 'equity_retained', false, '110', 130),
  ('FR', '119', 'Report à nouveau (solde débiteur)', '{}'::jsonb, 'equity_retained', false, '11', 140),
  ('FR', '119000', 'Report à nouveau débiteur', '{}'::jsonb, 'equity_retained', false, '119', 150),
  ('FR', '12', 'Résultat de l''exercice', '{}'::jsonb, 'equity', false, null, 160),
  ('FR', '120', 'Résultat de l''exercice (bénéfice)', '{}'::jsonb, 'equity', false, '12', 170),
  ('FR', '120000', 'Résultat de l''exercice — bénéfice', '{}'::jsonb, 'equity', false, '120', 180),
  ('FR', '129', 'Résultat de l''exercice (perte)', '{}'::jsonb, 'equity', false, '12', 190),
  ('FR', '129000', 'Résultat de l''exercice — perte', '{}'::jsonb, 'equity', false, '129', 200),
  ('FR', '13', 'Subventions d''investissement', '{}'::jsonb, 'equity', false, null, 210),
  ('FR', '131', 'Subventions d''équipement', '{}'::jsonb, 'equity', false, '13', 220),
  ('FR', '131000', 'Subventions d''équipement reçues', '{}'::jsonb, 'equity', false, '131', 230),
  ('FR', '139', 'Subventions d''investissement inscrites au compte de résultat', '{}'::jsonb, 'equity', false, '13', 240),
  ('FR', '14', 'Provisions réglementées', '{}'::jsonb, 'equity', false, null, 250),
  ('FR', '145', 'Amortissements dérogatoires', '{}'::jsonb, 'equity', false, '14', 260),
  ('FR', '148', 'Autres provisions réglementées', '{}'::jsonb, 'equity', false, '14', 270),
  ('FR', '15', 'Provisions', '{}'::jsonb, 'liability_non_current', false, null, 280),
  ('FR', '151', 'Provisions pour risques', '{}'::jsonb, 'liability_non_current', false, '15', 290),
  ('FR', '151100', 'Provisions pour litiges', '{}'::jsonb, 'liability_non_current', false, '151', 300),
  ('FR', '153', 'Provisions pour pensions et obligations similaires', '{}'::jsonb, 'liability_non_current', false, '15', 310),
  ('FR', '155', 'Provisions pour impôts', '{}'::jsonb, 'liability_non_current', false, '15', 320),
  ('FR', '158', 'Autres provisions pour charges', '{}'::jsonb, 'liability_non_current', false, '15', 330),
  ('FR', '158000', 'Autres provisions pour charges', '{}'::jsonb, 'liability_non_current', false, '158', 340),
  ('FR', '16', 'Emprunts et dettes assimilées', '{}'::jsonb, 'liability_non_current', false, null, 350),
  ('FR', '161', 'Emprunts obligataires convertibles', '{}'::jsonb, 'liability_non_current', false, '16', 360),
  ('FR', '164', 'Emprunts auprès des établissements de crédit', '{}'::jsonb, 'liability_non_current', false, '16', 370),
  ('FR', '164000', 'Emprunts auprès des établissements de crédit', '{}'::jsonb, 'liability_non_current', false, '164', 380),
  ('FR', '165', 'Dépôts et cautionnements reçus', '{}'::jsonb, 'liability_non_current', false, '16', 390),
  ('FR', '166', 'Participation des salariés aux résultats', '{}'::jsonb, 'liability_non_current', false, '16', 400),
  ('FR', '167', 'Emprunts et dettes assortis de conditions particulières', '{}'::jsonb, 'liability_non_current', false, '16', 410),
  ('FR', '168', 'Autres emprunts et dettes assimilées', '{}'::jsonb, 'liability_non_current', false, '16', 420),
  ('FR', '168800', 'Intérêts courus sur emprunts et dettes', '{}'::jsonb, 'liability_non_current', false, '168', 430),
  ('FR', '17', 'Dettes rattachées à des participations', '{}'::jsonb, 'liability_non_current', false, null, 440),
  ('FR', '171', 'Dettes rattachées à des participations (groupe)', '{}'::jsonb, 'liability_non_current', false, '17', 450),
  ('FR', '18', 'Comptes de liaison des établissements et sociétés en participation', '{}'::jsonb, 'liability_non_current', false, null, 460),
  ('FR', '181', 'Comptes de liaison des établissements', '{}'::jsonb, 'liability_non_current', false, '18', 470),
  ('FR', '20', 'Immobilisations incorporelles', '{}'::jsonb, 'asset_fixed', false, null, 480),
  ('FR', '201', 'Frais d''établissement', '{}'::jsonb, 'asset_fixed', false, '20', 490),
  ('FR', '203', 'Frais de recherche et de développement', '{}'::jsonb, 'asset_fixed', false, '20', 500),
  ('FR', '205', 'Concessions, brevets, licences, marques, procédés et logiciels', '{}'::jsonb, 'asset_fixed', false, '20', 510),
  ('FR', '205000', 'Concessions, brevets et droits similaires', '{}'::jsonb, 'asset_fixed', false, '205', 520),
  ('FR', '205100', 'Logiciels', '{}'::jsonb, 'asset_fixed', false, '205', 530),
  ('FR', '206', 'Droit au bail', '{}'::jsonb, 'asset_fixed', false, '20', 540),
  ('FR', '207', 'Fonds commercial', '{}'::jsonb, 'asset_fixed', false, '20', 550),
  ('FR', '208', 'Autres immobilisations incorporelles', '{}'::jsonb, 'asset_fixed', false, '20', 560),
  ('FR', '21', 'Immobilisations corporelles', '{}'::jsonb, 'asset_fixed', false, null, 570),
  ('FR', '211', 'Terrains', '{}'::jsonb, 'asset_fixed', false, '21', 580),
  ('FR', '211000', 'Terrains', '{}'::jsonb, 'asset_fixed', false, '211', 590),
  ('FR', '213', 'Constructions', '{}'::jsonb, 'asset_fixed', false, '21', 600),
  ('FR', '213000', 'Constructions sur sol propre', '{}'::jsonb, 'asset_fixed', false, '213', 610),
  ('FR', '213500', 'Installations générales et agencements des constructions', '{}'::jsonb, 'asset_fixed', false, '213', 620),
  ('FR', '215', 'Installations techniques, matériel et outillage industriels', '{}'::jsonb, 'asset_fixed', false, '21', 630),
  ('FR', '215400', 'Matériel industriel', '{}'::jsonb, 'asset_fixed', false, '215', 640),
  ('FR', '218', 'Autres immobilisations corporelles', '{}'::jsonb, 'asset_fixed', false, '21', 650),
  ('FR', '218100', 'Installations générales, agencements et aménagements divers', '{}'::jsonb, 'asset_fixed', false, '218', 660),
  ('FR', '218200', 'Matériel de transport', '{}'::jsonb, 'asset_fixed', false, '218', 670),
  ('FR', '218300', 'Matériel de bureau et matériel informatique', '{}'::jsonb, 'asset_fixed', false, '218', 680),
  ('FR', '218400', 'Mobilier', '{}'::jsonb, 'asset_fixed', false, '218', 690),
  ('FR', '22', 'Immobilisations mises en concession', '{}'::jsonb, 'asset_fixed', false, null, 700),
  ('FR', '23', 'Immobilisations en cours', '{}'::jsonb, 'asset_fixed', false, null, 710),
  ('FR', '231', 'Immobilisations corporelles en cours', '{}'::jsonb, 'asset_fixed', false, '23', 720),
  ('FR', '232', 'Immobilisations incorporelles en cours', '{}'::jsonb, 'asset_fixed', false, '23', 730),
  ('FR', '237', 'Avances et acomptes versés sur immobilisations incorporelles', '{}'::jsonb, 'asset_fixed', false, '23', 740),
  ('FR', '238', 'Avances et acomptes versés sur immobilisations corporelles', '{}'::jsonb, 'asset_fixed', false, '23', 750),
  ('FR', '26', 'Participations et créances rattachées à des participations', '{}'::jsonb, 'asset_non_current', false, null, 760),
  ('FR', '261', 'Titres de participation', '{}'::jsonb, 'asset_non_current', false, '26', 770),
  ('FR', '261000', 'Titres de participation', '{}'::jsonb, 'asset_non_current', false, '261', 780),
  ('FR', '267', 'Créances rattachées à des participations', '{}'::jsonb, 'asset_non_current', false, '26', 790),
  ('FR', '27', 'Autres immobilisations financières', '{}'::jsonb, 'asset_non_current', false, null, 800),
  ('FR', '271', 'Titres immobilisés (droit de propriété)', '{}'::jsonb, 'asset_non_current', false, '27', 810),
  ('FR', '274', 'Prêts', '{}'::jsonb, 'asset_non_current', false, '27', 820),
  ('FR', '275', 'Dépôts et cautionnements versés', '{}'::jsonb, 'asset_non_current', false, '27', 830),
  ('FR', '275000', 'Dépôts et cautionnements versés', '{}'::jsonb, 'asset_non_current', false, '275', 840),
  ('FR', '276', 'Autres créances immobilisées', '{}'::jsonb, 'asset_non_current', false, '27', 850),
  ('FR', '28', 'Amortissements des immobilisations', '{}'::jsonb, 'asset_fixed', false, null, 860),
  ('FR', '280', 'Amortissements des immobilisations incorporelles', '{}'::jsonb, 'asset_fixed', false, '28', 870),
  ('FR', '280100', 'Amortissements des frais d''établissement', '{}'::jsonb, 'asset_fixed', false, '280', 880),
  ('FR', '280500', 'Amortissements des concessions, brevets et logiciels', '{}'::jsonb, 'asset_fixed', false, '280', 890),
  ('FR', '281', 'Amortissements des immobilisations corporelles', '{}'::jsonb, 'asset_fixed', false, '28', 900),
  ('FR', '281300', 'Amortissements des constructions', '{}'::jsonb, 'asset_fixed', false, '281', 910),
  ('FR', '281500', 'Amortissements des installations techniques et du matériel industriel', '{}'::jsonb, 'asset_fixed', false, '281', 920),
  ('FR', '281810', 'Amortissements des installations générales et agencements divers', '{}'::jsonb, 'asset_fixed', false, '281', 930),
  ('FR', '281820', 'Amortissements du matériel de transport', '{}'::jsonb, 'asset_fixed', false, '281', 940),
  ('FR', '281830', 'Amortissements du matériel de bureau et informatique', '{}'::jsonb, 'asset_fixed', false, '281', 950),
  ('FR', '281840', 'Amortissements du mobilier', '{}'::jsonb, 'asset_fixed', false, '281', 960),
  ('FR', '29', 'Dépréciations des immobilisations', '{}'::jsonb, 'asset_fixed', false, null, 970),
  ('FR', '290', 'Dépréciations des immobilisations incorporelles', '{}'::jsonb, 'asset_fixed', false, '29', 980),
  ('FR', '291', 'Dépréciations des immobilisations corporelles', '{}'::jsonb, 'asset_fixed', false, '29', 990),
  ('FR', '31', 'Matières premières et fournitures', '{}'::jsonb, 'asset_current', false, null, 1000),
  ('FR', '310', 'Matières premières', '{}'::jsonb, 'asset_current', false, '31', 1010),
  ('FR', '310000', 'Matières premières', '{}'::jsonb, 'asset_current', false, '310', 1020),
  ('FR', '317', 'Fournitures', '{}'::jsonb, 'asset_current', false, '31', 1030),
  ('FR', '32', 'Autres approvisionnements', '{}'::jsonb, 'asset_current', false, null, 1040),
  ('FR', '321', 'Matières consommables', '{}'::jsonb, 'asset_current', false, '32', 1050),
  ('FR', '322', 'Fournitures consommables', '{}'::jsonb, 'asset_current', false, '32', 1060),
  ('FR', '322500', 'Fournitures de bureau', '{}'::jsonb, 'asset_current', false, '322', 1070),
  ('FR', '326', 'Emballages', '{}'::jsonb, 'asset_current', false, '32', 1080),
  ('FR', '33', 'En-cours de production de biens', '{}'::jsonb, 'asset_current', false, null, 1090),
  ('FR', '331', 'Produits en cours', '{}'::jsonb, 'asset_current', false, '33', 1100),
  ('FR', '335', 'Travaux en cours', '{}'::jsonb, 'asset_current', false, '33', 1110),
  ('FR', '34', 'En-cours de production de services', '{}'::jsonb, 'asset_current', false, null, 1120),
  ('FR', '341', 'Études en cours', '{}'::jsonb, 'asset_current', false, '34', 1130),
  ('FR', '345', 'Prestations de services en cours', '{}'::jsonb, 'asset_current', false, '34', 1140),
  ('FR', '35', 'Stocks de produits', '{}'::jsonb, 'asset_current', false, null, 1150),
  ('FR', '351', 'Produits intermédiaires', '{}'::jsonb, 'asset_current', false, '35', 1160),
  ('FR', '355', 'Produits finis', '{}'::jsonb, 'asset_current', false, '35', 1170),
  ('FR', '355000', 'Produits finis', '{}'::jsonb, 'asset_current', false, '355', 1180),
  ('FR', '358', 'Produits résiduels', '{}'::jsonb, 'asset_current', false, '35', 1190),
  ('FR', '37', 'Stocks de marchandises', '{}'::jsonb, 'asset_current', false, null, 1200),
  ('FR', '370', 'Stocks de marchandises', '{}'::jsonb, 'asset_current', false, '37', 1210),
  ('FR', '370000', 'Stocks de marchandises', '{}'::jsonb, 'asset_current', false, '370', 1220),
  ('FR', '39', 'Dépréciations des stocks et en-cours', '{}'::jsonb, 'asset_current', false, null, 1230),
  ('FR', '391', 'Dépréciations des matières premières et fournitures', '{}'::jsonb, 'asset_current', false, '39', 1240),
  ('FR', '397', 'Dépréciations des stocks de marchandises', '{}'::jsonb, 'asset_current', false, '39', 1250),
  ('FR', '397000', 'Dépréciations des stocks de marchandises', '{}'::jsonb, 'asset_current', false, '397', 1260),
  ('FR', '40', 'Fournisseurs et comptes rattachés', '{}'::jsonb, 'liability_payable', true, null, 1270),
  ('FR', '401', 'Fournisseurs', '{}'::jsonb, 'liability_payable', true, '40', 1280),
  ('FR', '401000', 'Fournisseurs', '{}'::jsonb, 'liability_payable', true, '401', 1290),
  ('FR', '401100', 'Fournisseurs — achats de biens et prestations de services', '{}'::jsonb, 'liability_payable', true, '401', 1300),
  ('FR', '403', 'Fournisseurs — Effets à payer', '{}'::jsonb, 'liability_current', false, '40', 1310),
  ('FR', '404', 'Fournisseurs d''immobilisations', '{}'::jsonb, 'liability_current', false, '40', 1320),
  ('FR', '405', 'Fournisseurs d''immobilisations — Effets à payer', '{}'::jsonb, 'liability_current', false, '40', 1330),
  ('FR', '408', 'Fournisseurs — Factures non parvenues', '{}'::jsonb, 'liability_current', false, '40', 1340),
  ('FR', '408100', 'Fournisseurs — factures non parvenues', '{}'::jsonb, 'liability_current', false, '408', 1350),
  ('FR', '409', 'Fournisseurs débiteurs', '{}'::jsonb, 'liability_current', false, '40', 1360),
  ('FR', '409100', 'Fournisseurs — avances et acomptes versés sur commandes', '{}'::jsonb, 'liability_current', false, '409', 1370),
  ('FR', '41', 'Clients et comptes rattachés', '{}'::jsonb, 'asset_receivable', true, null, 1380),
  ('FR', '411', 'Clients', '{}'::jsonb, 'asset_receivable', true, '41', 1390),
  ('FR', '411000', 'Clients — ventes de biens et prestations de services', '{}'::jsonb, 'asset_receivable', true, '411', 1400),
  ('FR', '413', 'Clients — Effets à recevoir', '{}'::jsonb, 'asset_current', false, '41', 1410),
  ('FR', '416', 'Clients douteux ou litigieux', '{}'::jsonb, 'asset_current', false, '41', 1420),
  ('FR', '416000', 'Clients douteux ou litigieux', '{}'::jsonb, 'asset_current', false, '416', 1430),
  ('FR', '418', 'Clients — Produits non encore facturés', '{}'::jsonb, 'asset_current', false, '41', 1440),
  ('FR', '418100', 'Clients — factures à établir', '{}'::jsonb, 'asset_current', false, '418', 1450),
  ('FR', '419', 'Clients créditeurs', '{}'::jsonb, 'asset_current', false, '41', 1460),
  ('FR', '419100', 'Clients — avances et acomptes reçus sur commandes', '{}'::jsonb, 'asset_current', false, '419', 1470),
  ('FR', '42', 'Personnel et comptes rattachés', '{}'::jsonb, 'liability_current', false, null, 1480),
  ('FR', '421', 'Personnel — Rémunérations dues', '{}'::jsonb, 'liability_current', false, '42', 1490),
  ('FR', '421000', 'Personnel — rémunérations dues', '{}'::jsonb, 'liability_current', false, '421', 1500),
  ('FR', '425', 'Personnel — Avances et acomptes', '{}'::jsonb, 'liability_current', false, '42', 1510),
  ('FR', '425000', 'Personnel — avances et acomptes', '{}'::jsonb, 'liability_current', false, '425', 1520),
  ('FR', '427', 'Personnel — Oppositions', '{}'::jsonb, 'liability_current', false, '42', 1530),
  ('FR', '428', 'Personnel — Charges à payer et produits à recevoir', '{}'::jsonb, 'liability_current', false, '42', 1540),
  ('FR', '428200', 'Dettes provisionnées pour congés à payer', '{}'::jsonb, 'liability_current', false, '428', 1550),
  ('FR', '428600', 'Personnel — autres charges à payer', '{}'::jsonb, 'liability_current', false, '428', 1560),
  ('FR', '43', 'Sécurité sociale et autres organismes sociaux', '{}'::jsonb, 'liability_current', false, null, 1570),
  ('FR', '431', 'Sécurité sociale', '{}'::jsonb, 'liability_current', false, '43', 1580),
  ('FR', '431000', 'URSSAF — cotisations à payer', '{}'::jsonb, 'liability_current', false, '431', 1590),
  ('FR', '437', 'Autres organismes sociaux', '{}'::jsonb, 'liability_current', false, '43', 1600),
  ('FR', '437100', 'Caisses de retraite complémentaire', '{}'::jsonb, 'liability_current', false, '437', 1610),
  ('FR', '437200', 'Mutuelle et organismes de prévoyance', '{}'::jsonb, 'liability_current', false, '437', 1620),
  ('FR', '438', 'Organismes sociaux — Charges à payer et produits à recevoir', '{}'::jsonb, 'liability_current', false, '43', 1630),
  ('FR', '44', 'État et autres collectivités publiques', '{}'::jsonb, 'liability_current', false, null, 1640),
  ('FR', '441', 'État — Subventions à recevoir', '{}'::jsonb, 'asset_current', false, '44', 1650),
  ('FR', '444', 'État — Impôt sur les bénéfices', '{}'::jsonb, 'liability_current', false, '44', 1660),
  ('FR', '444000', 'État — impôt sur les bénéfices', '{}'::jsonb, 'liability_current', false, '444', 1670),
  ('FR', '445', 'État — Taxes sur le chiffre d''affaires', '{}'::jsonb, 'liability_current', false, '44', 1680),
  ('FR', '445200', 'TVA due intracommunautaire', '{}'::jsonb, 'liability_current', false, '445', 1690),
  ('FR', '445510', 'TVA à décaisser', '{}'::jsonb, 'liability_current', false, '445', 1700),
  ('FR', '445660', 'TVA déductible sur autres biens et services', '{}'::jsonb, 'asset_current', false, '445', 1710),
  ('FR', '445662', 'TVA déductible sur immobilisations', '{}'::jsonb, 'asset_current', false, '445', 1720),
  ('FR', '445670', 'Crédit de TVA à reporter', '{}'::jsonb, 'asset_current', false, '445', 1730),
  ('FR', '445710', 'TVA collectée', '{}'::jsonb, 'liability_current', false, '445', 1740),
  ('FR', '445800', 'Taxes sur le chiffre d''affaires à régulariser ou en attente', '{}'::jsonb, 'asset_current', false, '445', 1750),
  ('FR', '447', 'Autres impôts, taxes et versements assimilés', '{}'::jsonb, 'liability_current', false, '44', 1760),
  ('FR', '447000', 'Autres impôts, taxes et versements assimilés', '{}'::jsonb, 'liability_current', false, '447', 1770),
  ('FR', '448', 'État — Charges à payer et produits à recevoir', '{}'::jsonb, 'liability_current', false, '44', 1780),
  ('FR', '45', 'Groupe et associés', '{}'::jsonb, 'liability_current', false, null, 1790),
  ('FR', '451', 'Groupe', '{}'::jsonb, 'liability_current', false, '45', 1800),
  ('FR', '455', 'Associés — Comptes courants', '{}'::jsonb, 'liability_current', false, '45', 1810),
  ('FR', '455000', 'Associés — comptes courants', '{}'::jsonb, 'liability_current', false, '455', 1820),
  ('FR', '456', 'Associés — Opérations sur le capital', '{}'::jsonb, 'liability_current', false, '45', 1830),
  ('FR', '457', 'Associés — Dividendes à payer', '{}'::jsonb, 'liability_current', false, '45', 1840),
  ('FR', '457000', 'Associés — dividendes à payer', '{}'::jsonb, 'liability_current', false, '457', 1850),
  ('FR', '46', 'Débiteurs divers et créditeurs divers', '{}'::jsonb, 'liability_current', false, null, 1860),
  ('FR', '462', 'Créances sur cessions d''immobilisations', '{}'::jsonb, 'asset_current', false, '46', 1870),
  ('FR', '465', 'Créances sur cessions de valeurs mobilières de placement', '{}'::jsonb, 'asset_current', false, '46', 1880),
  ('FR', '467', 'Autres comptes débiteurs ou créditeurs', '{}'::jsonb, 'liability_current', false, '46', 1890),
  ('FR', '467000', 'Autres comptes débiteurs ou créditeurs', '{}'::jsonb, 'liability_current', false, '467', 1900),
  ('FR', '468', 'Divers — Charges à payer et produits à recevoir', '{}'::jsonb, 'liability_current', false, '46', 1910),
  ('FR', '468600', 'Divers — charges à payer', '{}'::jsonb, 'liability_current', false, '468', 1920),
  ('FR', '47', 'Comptes transitoires ou d''attente', '{}'::jsonb, 'liability_current', false, null, 1930),
  ('FR', '471', 'Comptes d''attente', '{}'::jsonb, 'liability_current', false, '47', 1940),
  ('FR', '471000', 'Compte d''attente', '{}'::jsonb, 'liability_current', false, '471', 1950),
  ('FR', '478', 'Autres comptes transitoires', '{}'::jsonb, 'liability_current', false, '47', 1960),
  ('FR', '48', 'Comptes de régularisation', '{}'::jsonb, 'liability_current', false, null, 1970),
  ('FR', '486', 'Charges constatées d''avance', '{}'::jsonb, 'asset_prepayments', false, '48', 1980),
  ('FR', '486000', 'Charges constatées d''avance', '{}'::jsonb, 'asset_prepayments', false, '486', 1990),
  ('FR', '487', 'Produits constatés d''avance', '{}'::jsonb, 'liability_current', false, '48', 2000),
  ('FR', '487000', 'Produits constatés d''avance', '{}'::jsonb, 'liability_current', false, '487', 2010),
  ('FR', '49', 'Dépréciations des comptes de tiers', '{}'::jsonb, 'asset_current', false, null, 2020),
  ('FR', '491', 'Dépréciations des comptes de clients', '{}'::jsonb, 'asset_current', false, '49', 2030),
  ('FR', '491000', 'Dépréciations des comptes de clients', '{}'::jsonb, 'asset_current', false, '491', 2040),
  ('FR', '50', 'Valeurs mobilières de placement', '{}'::jsonb, 'asset_current', false, null, 2050),
  ('FR', '501', 'Parts dans des entreprises liées', '{}'::jsonb, 'asset_current', false, '50', 2060),
  ('FR', '503', 'Actions', '{}'::jsonb, 'asset_current', false, '50', 2070),
  ('FR', '506', 'Obligations', '{}'::jsonb, 'asset_current', false, '50', 2080),
  ('FR', '508', 'Autres valeurs mobilières de placement et créances assimilées', '{}'::jsonb, 'asset_current', false, '50', 2090),
  ('FR', '51', 'Banques, établissements financiers et assimilés', '{}'::jsonb, 'asset_current', false, null, 2100),
  ('FR', '511', 'Valeurs à l''encaissement', '{}'::jsonb, 'asset_current', false, '51', 2110),
  ('FR', '511300', 'Chèques à encaisser', '{}'::jsonb, 'asset_current', false, '511', 2120),
  ('FR', '512', 'Banques', '{}'::jsonb, 'asset_cash', false, '51', 2130),
  ('FR', '512000', 'Banque', '{}'::jsonb, 'asset_cash', false, '512', 2140),
  ('FR', '512100', 'Banque — compte courant', '{}'::jsonb, 'asset_cash', false, '512', 2150),
  ('FR', '512500', 'Banque — compte en devises', '{}'::jsonb, 'asset_cash', false, '512', 2160),
  ('FR', '514', 'Chèques postaux', '{}'::jsonb, 'asset_current', false, '51', 2170),
  ('FR', '517', 'Autres organismes financiers', '{}'::jsonb, 'asset_current', false, '51', 2180),
  ('FR', '518', 'Intérêts courus', '{}'::jsonb, 'asset_current', false, '51', 2190),
  ('FR', '52', 'Instruments de trésorerie', '{}'::jsonb, 'asset_current', false, null, 2200),
  ('FR', '53', 'Caisse', '{}'::jsonb, 'asset_cash', false, null, 2210),
  ('FR', '530', 'Caisse', '{}'::jsonb, 'asset_cash', false, '53', 2220),
  ('FR', '530000', 'Caisse', '{}'::jsonb, 'asset_cash', false, '530', 2230),
  ('FR', '54', 'Régies d''avances et accréditifs', '{}'::jsonb, 'asset_current', false, null, 2240),
  ('FR', '540', 'Régies d''avances et accréditifs', '{}'::jsonb, 'asset_current', false, '54', 2250),
  ('FR', '58', 'Virements internes', '{}'::jsonb, 'asset_current', false, null, 2260),
  ('FR', '580', 'Virements internes', '{}'::jsonb, 'asset_current', false, '58', 2270),
  ('FR', '580000', 'Virements internes', '{}'::jsonb, 'asset_current', false, '580', 2280),
  ('FR', '59', 'Dépréciations des comptes financiers', '{}'::jsonb, 'asset_current', false, null, 2290),
  ('FR', '590', 'Dépréciations des valeurs mobilières de placement', '{}'::jsonb, 'asset_current', false, '59', 2300),
  ('FR', '60', 'Achats', '{}'::jsonb, 'expense_direct_cost', false, null, 2310),
  ('FR', '601', 'Achats stockés — Matières premières et fournitures', '{}'::jsonb, 'expense_direct_cost', false, '60', 2320),
  ('FR', '601000', 'Achats de matières premières', '{}'::jsonb, 'expense_direct_cost', false, '601', 2330),
  ('FR', '602', 'Achats stockés — Autres approvisionnements', '{}'::jsonb, 'expense_direct_cost', false, '60', 2340),
  ('FR', '603', 'Variation des stocks', '{}'::jsonb, 'expense_direct_cost', false, '60', 2350),
  ('FR', '603100', 'Variation des stocks de matières premières', '{}'::jsonb, 'expense_direct_cost', false, '603', 2360),
  ('FR', '603700', 'Variation des stocks de marchandises', '{}'::jsonb, 'expense_direct_cost', false, '603', 2370),
  ('FR', '604', 'Achats d''études et prestations de services', '{}'::jsonb, 'expense_direct_cost', false, '60', 2380),
  ('FR', '605', 'Achats de matériel, équipements et travaux', '{}'::jsonb, 'expense_direct_cost', false, '60', 2390),
  ('FR', '606', 'Achats non stockés de matières et fournitures', '{}'::jsonb, 'expense_direct_cost', false, '60', 2400),
  ('FR', '606100', 'Fournitures non stockables — eau et énergie', '{}'::jsonb, 'expense_direct_cost', false, '606', 2410),
  ('FR', '606300', 'Fournitures d''entretien et de petit équipement', '{}'::jsonb, 'expense_direct_cost', false, '606', 2420),
  ('FR', '606400', 'Fournitures administratives', '{}'::jsonb, 'expense_direct_cost', false, '606', 2430),
  ('FR', '607', 'Achats de marchandises', '{}'::jsonb, 'expense_direct_cost', false, '60', 2440),
  ('FR', '607000', 'Achats de marchandises', '{}'::jsonb, 'expense_direct_cost', false, '607', 2450),
  ('FR', '608', 'Frais accessoires d''achat', '{}'::jsonb, 'expense_direct_cost', false, '60', 2460),
  ('FR', '609', 'Rabais, remises et ristournes obtenus sur achats', '{}'::jsonb, 'expense_direct_cost', false, '60', 2470),
  ('FR', '61', 'Services extérieurs', '{}'::jsonb, 'expense', false, null, 2480),
  ('FR', '611', 'Sous-traitance générale', '{}'::jsonb, 'expense', false, '61', 2490),
  ('FR', '611000', 'Sous-traitance générale', '{}'::jsonb, 'expense', false, '611', 2500),
  ('FR', '612', 'Redevances de crédit-bail', '{}'::jsonb, 'expense', false, '61', 2510),
  ('FR', '613', 'Locations', '{}'::jsonb, 'expense', false, '61', 2520),
  ('FR', '613200', 'Locations immobilières', '{}'::jsonb, 'expense', false, '613', 2530),
  ('FR', '613500', 'Locations mobilières', '{}'::jsonb, 'expense', false, '613', 2540),
  ('FR', '614', 'Charges locatives et de copropriété', '{}'::jsonb, 'expense', false, '61', 2550),
  ('FR', '615', 'Entretien et réparations', '{}'::jsonb, 'expense', false, '61', 2560),
  ('FR', '615200', 'Entretien et réparations sur biens immobiliers', '{}'::jsonb, 'expense', false, '615', 2570),
  ('FR', '615500', 'Entretien et réparations sur biens mobiliers', '{}'::jsonb, 'expense', false, '615', 2580),
  ('FR', '615600', 'Maintenance', '{}'::jsonb, 'expense', false, '615', 2590),
  ('FR', '616', 'Primes d''assurances', '{}'::jsonb, 'expense', false, '61', 2600),
  ('FR', '616000', 'Primes d''assurances', '{}'::jsonb, 'expense', false, '616', 2610),
  ('FR', '617', 'Études et recherches', '{}'::jsonb, 'expense', false, '61', 2620),
  ('FR', '618', 'Divers', '{}'::jsonb, 'expense', false, '61', 2630),
  ('FR', '618100', 'Documentation générale', '{}'::jsonb, 'expense', false, '618', 2640),
  ('FR', '619', 'Rabais, remises et ristournes obtenus sur services extérieurs', '{}'::jsonb, 'expense', false, '61', 2650),
  ('FR', '62', 'Autres services extérieurs', '{}'::jsonb, 'expense', false, null, 2660),
  ('FR', '621', 'Personnel extérieur à l''entreprise', '{}'::jsonb, 'expense', false, '62', 2670),
  ('FR', '622', 'Rémunérations d''intermédiaires et honoraires', '{}'::jsonb, 'expense', false, '62', 2680),
  ('FR', '622600', 'Honoraires', '{}'::jsonb, 'expense', false, '622', 2690),
  ('FR', '622700', 'Frais d''actes et de contentieux', '{}'::jsonb, 'expense', false, '622', 2700),
  ('FR', '623', 'Publicité, publications et relations publiques', '{}'::jsonb, 'expense', false, '62', 2710),
  ('FR', '623100', 'Annonces et insertions', '{}'::jsonb, 'expense', false, '623', 2720),
  ('FR', '624', 'Transports de biens et transports collectifs du personnel', '{}'::jsonb, 'expense', false, '62', 2730),
  ('FR', '625', 'Déplacements, missions et réceptions', '{}'::jsonb, 'expense', false, '62', 2740),
  ('FR', '625100', 'Voyages et déplacements', '{}'::jsonb, 'expense', false, '625', 2750),
  ('FR', '625600', 'Missions', '{}'::jsonb, 'expense', false, '625', 2760),
  ('FR', '625700', 'Réceptions', '{}'::jsonb, 'expense', false, '625', 2770),
  ('FR', '626', 'Frais postaux et de télécommunications', '{}'::jsonb, 'expense', false, '62', 2780),
  ('FR', '626100', 'Frais de télécommunications', '{}'::jsonb, 'expense', false, '626', 2790),
  ('FR', '627', 'Services bancaires et assimilés', '{}'::jsonb, 'expense', false, '62', 2800),
  ('FR', '627000', 'Services bancaires et assimilés', '{}'::jsonb, 'expense', false, '627', 2810),
  ('FR', '628', 'Divers', '{}'::jsonb, 'expense', false, '62', 2820),
  ('FR', '628100', 'Concours divers — cotisations', '{}'::jsonb, 'expense', false, '628', 2830),
  ('FR', '629', 'Rabais, remises et ristournes obtenus sur autres services extérieurs', '{}'::jsonb, 'expense', false, '62', 2840),
  ('FR', '63', 'Impôts, taxes et versements assimilés', '{}'::jsonb, 'expense', false, null, 2850),
  ('FR', '631', 'Impôts et taxes sur rémunérations (administration des impôts)', '{}'::jsonb, 'expense', false, '63', 2860),
  ('FR', '633', 'Impôts et taxes sur rémunérations (autres organismes)', '{}'::jsonb, 'expense', false, '63', 2870),
  ('FR', '633300', 'Formation professionnelle continue', '{}'::jsonb, 'expense', false, '633', 2880),
  ('FR', '635', 'Autres impôts et taxes (administration des impôts)', '{}'::jsonb, 'expense', false, '63', 2890),
  ('FR', '635100', 'Contribution économique territoriale', '{}'::jsonb, 'expense', false, '635', 2900),
  ('FR', '637', 'Autres impôts et taxes (autres organismes)', '{}'::jsonb, 'expense', false, '63', 2910),
  ('FR', '64', 'Charges de personnel', '{}'::jsonb, 'expense', false, null, 2920),
  ('FR', '641', 'Rémunérations du personnel', '{}'::jsonb, 'expense', false, '64', 2930),
  ('FR', '641000', 'Rémunérations du personnel', '{}'::jsonb, 'expense', false, '641', 2940),
  ('FR', '641100', 'Salaires et appointements', '{}'::jsonb, 'expense', false, '641', 2950),
  ('FR', '641400', 'Indemnités et avantages divers', '{}'::jsonb, 'expense', false, '641', 2960),
  ('FR', '644', 'Rémunération du travail de l''exploitant', '{}'::jsonb, 'expense', false, '64', 2970),
  ('FR', '645', 'Charges de sécurité sociale et de prévoyance', '{}'::jsonb, 'expense', false, '64', 2980),
  ('FR', '645100', 'Cotisations à l''URSSAF', '{}'::jsonb, 'expense', false, '645', 2990),
  ('FR', '645300', 'Cotisations aux caisses de retraite', '{}'::jsonb, 'expense', false, '645', 3000),
  ('FR', '647', 'Autres charges sociales', '{}'::jsonb, 'expense', false, '64', 3010),
  ('FR', '647500', 'Médecine du travail et pharmacie', '{}'::jsonb, 'expense', false, '647', 3020),
  ('FR', '648', 'Autres charges de personnel', '{}'::jsonb, 'expense', false, '64', 3030),
  ('FR', '65', 'Autres charges de gestion courante', '{}'::jsonb, 'expense', false, null, 3040),
  ('FR', '651', 'Redevances pour concessions, brevets, licences et marques', '{}'::jsonb, 'expense', false, '65', 3050),
  ('FR', '653', 'Jetons de présence', '{}'::jsonb, 'expense', false, '65', 3060),
  ('FR', '654', 'Pertes sur créances irrécouvrables', '{}'::jsonb, 'expense', false, '65', 3070),
  ('FR', '655', 'Quote-part de résultat sur opérations faites en commun', '{}'::jsonb, 'expense', false, '65', 3080),
  ('FR', '658', 'Charges diverses de gestion courante', '{}'::jsonb, 'expense', false, '65', 3090),
  ('FR', '658000', 'Charges diverses de gestion courante', '{}'::jsonb, 'expense', false, '658', 3100),
  ('FR', '66', 'Charges financières', '{}'::jsonb, 'expense', false, null, 3110),
  ('FR', '661', 'Charges d''intérêts', '{}'::jsonb, 'expense', false, '66', 3120),
  ('FR', '661600', 'Intérêts des emprunts et dettes', '{}'::jsonb, 'expense', false, '661', 3130),
  ('FR', '664', 'Pertes sur créances liées à des participations', '{}'::jsonb, 'expense', false, '66', 3140),
  ('FR', '665', 'Escomptes accordés', '{}'::jsonb, 'expense', false, '66', 3150),
  ('FR', '666', 'Pertes de change', '{}'::jsonb, 'expense', false, '66', 3160),
  ('FR', '666000', 'Pertes de change', '{}'::jsonb, 'expense', false, '666', 3170),
  ('FR', '667', 'Charges nettes sur cessions de valeurs mobilières de placement', '{}'::jsonb, 'expense', false, '66', 3180),
  ('FR', '668', 'Autres charges financières', '{}'::jsonb, 'expense', false, '66', 3190),
  ('FR', '67', 'Charges exceptionnelles', '{}'::jsonb, 'expense', false, null, 3200),
  ('FR', '671', 'Charges exceptionnelles sur opérations de gestion', '{}'::jsonb, 'expense', false, '67', 3210),
  ('FR', '671200', 'Pénalités, amendes fiscales et pénales', '{}'::jsonb, 'expense', false, '671', 3220),
  ('FR', '675', 'Valeurs comptables des éléments d''actif cédés', '{}'::jsonb, 'expense', false, '67', 3230),
  ('FR', '675000', 'Valeurs comptables des éléments d''actif cédés', '{}'::jsonb, 'expense', false, '675', 3240),
  ('FR', '678', 'Autres charges exceptionnelles', '{}'::jsonb, 'expense', false, '67', 3250),
  ('FR', '68', 'Dotations aux amortissements, dépréciations et provisions', '{}'::jsonb, 'expense_depreciation', false, null, 3260),
  ('FR', '681', 'Dotations aux amortissements et provisions — charges d''exploitation', '{}'::jsonb, 'expense_depreciation', false, '68', 3270),
  ('FR', '681100', 'Dotations aux amortissements sur immobilisations', '{}'::jsonb, 'expense_depreciation', false, '681', 3280),
  ('FR', '681500', 'Dotations aux provisions pour risques et charges d''exploitation', '{}'::jsonb, 'expense_depreciation', false, '681', 3290),
  ('FR', '681700', 'Dotations aux dépréciations des actifs circulants', '{}'::jsonb, 'expense_depreciation', false, '681', 3300),
  ('FR', '686', 'Dotations aux amortissements et provisions — charges financières', '{}'::jsonb, 'expense_depreciation', false, '68', 3310),
  ('FR', '687', 'Dotations aux amortissements et provisions — charges exceptionnelles', '{}'::jsonb, 'expense_depreciation', false, '68', 3320),
  ('FR', '687200', 'Dotations aux amortissements dérogatoires', '{}'::jsonb, 'expense_depreciation', false, '687', 3330),
  ('FR', '69', 'Participation des salariés et impôts sur les bénéfices', '{}'::jsonb, 'expense', false, null, 3340),
  ('FR', '691', 'Participation des salariés aux résultats', '{}'::jsonb, 'expense', false, '69', 3350),
  ('FR', '695', 'Impôts sur les bénéfices', '{}'::jsonb, 'expense', false, '69', 3360),
  ('FR', '695000', 'Impôts sur les bénéfices', '{}'::jsonb, 'expense', false, '695', 3370),
  ('FR', '696', 'Suppléments d''impôt sur les sociétés liés aux distributions', '{}'::jsonb, 'expense', false, '69', 3380),
  ('FR', '698', 'Intégration fiscale', '{}'::jsonb, 'expense', false, '69', 3390),
  ('FR', '70', 'Ventes de produits fabriqués, prestations de services, marchandises', '{}'::jsonb, 'income', false, null, 3400),
  ('FR', '701', 'Ventes de produits finis', '{}'::jsonb, 'income', false, '70', 3410),
  ('FR', '704', 'Travaux', '{}'::jsonb, 'income', false, '70', 3420),
  ('FR', '704000', 'Travaux', '{}'::jsonb, 'income', false, '704', 3430),
  ('FR', '705', 'Études', '{}'::jsonb, 'income', false, '70', 3440),
  ('FR', '705000', 'Études', '{}'::jsonb, 'income', false, '705', 3450),
  ('FR', '706', 'Prestations de services', '{}'::jsonb, 'income', false, '70', 3460),
  ('FR', '706000', 'Prestations de services', '{}'::jsonb, 'income', false, '706', 3470),
  ('FR', '707', 'Ventes de marchandises', '{}'::jsonb, 'income', false, '70', 3480),
  ('FR', '707000', 'Ventes de marchandises', '{}'::jsonb, 'income', false, '707', 3490),
  ('FR', '708', 'Produits des activités annexes', '{}'::jsonb, 'income', false, '70', 3500),
  ('FR', '708500', 'Ports et frais accessoires facturés', '{}'::jsonb, 'income', false, '708', 3510),
  ('FR', '709', 'Rabais, remises et ristournes accordés par l''entreprise', '{}'::jsonb, 'income', false, '70', 3520),
  ('FR', '709000', 'Rabais, remises et ristournes accordés', '{}'::jsonb, 'income', false, '709', 3530),
  ('FR', '71', 'Production stockée (ou déstockage)', '{}'::jsonb, 'income_other', false, null, 3540),
  ('FR', '713', 'Variation des stocks (en-cours de production, produits)', '{}'::jsonb, 'income_other', false, '71', 3550),
  ('FR', '713500', 'Variation des stocks de produits finis', '{}'::jsonb, 'income_other', false, '713', 3560),
  ('FR', '72', 'Production immobilisée', '{}'::jsonb, 'income_other', false, null, 3570),
  ('FR', '721', 'Production immobilisée — immobilisations incorporelles', '{}'::jsonb, 'income_other', false, '72', 3580),
  ('FR', '722', 'Production immobilisée — immobilisations corporelles', '{}'::jsonb, 'income_other', false, '72', 3590),
  ('FR', '73', 'Produits nets partiels sur opérations à long terme', '{}'::jsonb, 'income_other', false, null, 3600),
  ('FR', '734', 'Produits nets sur opérations à long terme', '{}'::jsonb, 'income_other', false, '73', 3610),
  ('FR', '74', 'Subventions d''exploitation', '{}'::jsonb, 'income_other', false, null, 3620),
  ('FR', '740', 'Subventions d''exploitation', '{}'::jsonb, 'income_other', false, '74', 3630),
  ('FR', '740000', 'Subventions d''exploitation', '{}'::jsonb, 'income_other', false, '740', 3640),
  ('FR', '75', 'Autres produits de gestion courante', '{}'::jsonb, 'income_other', false, null, 3650),
  ('FR', '751', 'Redevances pour concessions, brevets, licences et marques', '{}'::jsonb, 'income_other', false, '75', 3660),
  ('FR', '752', 'Revenus des immeubles non affectés aux activités professionnelles', '{}'::jsonb, 'income_other', false, '75', 3670),
  ('FR', '755', 'Quote-part de résultat sur opérations faites en commun', '{}'::jsonb, 'income_other', false, '75', 3680),
  ('FR', '758', 'Produits divers de gestion courante', '{}'::jsonb, 'income_other', false, '75', 3690),
  ('FR', '758000', 'Produits divers de gestion courante', '{}'::jsonb, 'income_other', false, '758', 3700),
  ('FR', '76', 'Produits financiers', '{}'::jsonb, 'income_other', false, null, 3710),
  ('FR', '761', 'Produits de participations', '{}'::jsonb, 'income_other', false, '76', 3720),
  ('FR', '762', 'Produits des autres immobilisations financières', '{}'::jsonb, 'income_other', false, '76', 3730),
  ('FR', '763', 'Revenus des autres créances', '{}'::jsonb, 'income_other', false, '76', 3740),
  ('FR', '764', 'Revenus des valeurs mobilières de placement', '{}'::jsonb, 'income_other', false, '76', 3750),
  ('FR', '765', 'Escomptes obtenus', '{}'::jsonb, 'income_other', false, '76', 3760),
  ('FR', '766', 'Gains de change', '{}'::jsonb, 'income_other', false, '76', 3770),
  ('FR', '766000', 'Gains de change', '{}'::jsonb, 'income_other', false, '766', 3780),
  ('FR', '768', 'Autres produits financiers', '{}'::jsonb, 'income_other', false, '76', 3790),
  ('FR', '77', 'Produits exceptionnels', '{}'::jsonb, 'income_other', false, null, 3800),
  ('FR', '771', 'Produits exceptionnels sur opérations de gestion', '{}'::jsonb, 'income_other', false, '77', 3810),
  ('FR', '775', 'Produits des cessions d''éléments d''actif', '{}'::jsonb, 'income_other', false, '77', 3820),
  ('FR', '775000', 'Produits des cessions d''éléments d''actif', '{}'::jsonb, 'income_other', false, '775', 3830),
  ('FR', '777', 'Quote-part des subventions d''investissement virée au résultat', '{}'::jsonb, 'income_other', false, '77', 3840),
  ('FR', '778', 'Autres produits exceptionnels', '{}'::jsonb, 'income_other', false, '77', 3850),
  ('FR', '78', 'Reprises sur amortissements, dépréciations et provisions', '{}'::jsonb, 'income_other', false, null, 3860),
  ('FR', '781', 'Reprises sur amortissements et provisions (exploitation)', '{}'::jsonb, 'income_other', false, '78', 3870),
  ('FR', '786', 'Reprises sur dépréciations et provisions (financières)', '{}'::jsonb, 'income_other', false, '78', 3880),
  ('FR', '79', 'Transferts de charges', '{}'::jsonb, 'income_other', false, null, 3890),
  ('FR', '791', 'Transferts de charges d''exploitation', '{}'::jsonb, 'income_other', false, '79', 3900),
  ('FR', '791000', 'Transferts de charges d''exploitation', '{}'::jsonb, 'income_other', false, '791', 3910),
  ('FR', '796', 'Transferts de charges financières', '{}'::jsonb, 'income_other', false, '79', 3920)
on conflict (country, code) do update set
  name         = excluded.name,
  name_i18n    = excluded.name_i18n,
  account_type = excluded.account_type,
  reconcilable = excluded.reconcilable,
  parent_code  = excluded.parent_code,
  sequence     = excluded.sequence;

insert into journal_templates (country, code, name, journal_type, sequence) values
  ('FR', 'BNK', 'Journal de banque', 'bank', 30),
  ('FR', 'CSH', 'Journal de caisse', 'cash', 40),
  ('FR', 'MISC', 'Opérations diverses', 'general', 50),
  ('FR', 'OPN', 'Journal des à-nouveaux', 'opening', 60),
  ('FR', 'PUR', 'Journal des achats', 'purchase', 20),
  ('FR', 'SAL', 'Journal des ventes', 'sales', 10)
on conflict (country, code) do update set
  name         = excluded.name,
  journal_type = excluded.journal_type,
  sequence     = excluded.sequence;

insert into tax_templates
  (country, code, name, description, amount_type, amount, applies_to, treatment,
   valid_from, valid_to, legal_reference, vat_category, exemption_code, sequence,
   tax_kind, recoverable, jurisdiction, price_include, cash_basis,
   cash_basis_transition_account_code)
values
  ('FR', 'FR-P-00', 'Achat exonere', 'Sans TVA', 'percent', 0, 'purchase', 'exempt', date '1993-01-01', null, 'CGI, art. 261', 'E', 'VATEX-EU-132', 150, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-055', 'Achat 5,5 %', 'Autres biens et services', 'percent', 5.5, 'purchase', 'domestic', date '2014-01-01', null, 'CGI, art. 278-0 bis', 'S', null, 140, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-10', 'Achat 10 %', 'Autres biens et services', 'percent', 10, 'purchase', 'domestic', date '2014-01-01', null, 'CGI, art. 278 bis', 'S', null, 130, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-20', 'Achat 20 %', 'Autres biens et services', 'percent', 20, 'purchase', 'domestic', date '2014-01-01', null, 'CGI, art. 278', 'S', null, 110, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-20-CARB', 'Carburant vehicule de tourisme 20 % — deduction 80 %', 'Essences et gazoles des vehicules exclus du droit a deduction. La TVA non deductible suit le compte de la ligne ; la CA3 ne porte aucune grille de base a l''entree.', 'percent', 20, 'purchase', 'domestic', date '2021-01-01', null, 'CGI, art. 298, 4, 1 a et b', 'S', null, 200, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-20-I', 'Achat immobilisation 20 %', 'Immobilisations', 'percent', 20, 'purchase', 'domestic', date '2014-01-01', null, 'CGI, art. 278', 'S', null, 120, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-AL-20', 'Achat autoliquidation 20 %', 'Assujetti non etabli, lignes 3C/08/20', 'percent', 20, 'purchase', 'domestic_reverse_charge', date '2014-01-01', null, 'CGI, art. 283-1', 'AE', 'VATEX-EU-AE', 180, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-ICG-20', 'Acquisition intracom. biens 20 %', 'Autoliquidation, lignes 03/08/20', 'percent', 20, 'purchase', 'intracom_acquisition_goods', date '1993-01-01', null, 'CGI, art. 256 bis', 'AE', 'VATEX-EU-AE', 160, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-ICS-20', 'Service intracom. recu 20 %', 'Autoliquidation, lignes 2A/08/20', 'percent', 20, 'purchase', 'intracom_acquisition_services', date '2010-01-01', null, 'CGI, art. 283-2', 'AE', 'VATEX-EU-AE', 170, 'vat', true, null, false, false, null),
  ('FR', 'FR-P-IMP-20', 'Importation autoliquidee 20 %', 'Lignes 3A/08/20', 'percent', 20, 'purchase', 'import', date '2022-01-01', null, 'CGI, art. 293 A', 'S', null, 190, 'vat', true, null, false, false, null),
  ('FR', 'FR-S-021', 'Vente 2,1 %', 'Taux particulier', 'percent', 2.1, 'sale', 'domestic', date '2014-01-01', null, 'CGI, art. 281 quater', 'S', null, 40, 'vat', true, null, false, false, null),
  ('FR', 'FR-S-055', 'Vente 5,5 %', 'Taux reduit', 'percent', 5.5, 'sale', 'domestic', date '2014-01-01', null, 'CGI, art. 278-0 bis', 'S', null, 30, 'vat', true, null, false, false, null),
  ('FR', 'FR-S-10', 'Vente 10 %', 'Taux reduit', 'percent', 10, 'sale', 'domestic', date '2014-01-01', null, 'CGI, art. 278 bis', 'S', null, 20, 'vat', true, null, false, false, null),
  ('FR', 'FR-S-20', 'Vente 20 %', 'Taux normal', 'percent', 20, 'sale', 'domestic', date '2014-01-01', null, 'CGI, art. 278', 'S', null, 10, 'vat', true, null, false, false, null),
  ('FR', 'FR-S-AL', 'Vente autoliquidation', 'TVA due par le preneur', 'percent', 0, 'sale', 'domestic_reverse_charge', date '2014-01-01', null, 'CGI, art. 283-2 nonies', 'AE', 'VATEX-EU-AE', 50, 'vat', true, null, false, false, null),
  ('FR', 'FR-S-EXP', 'Exportation hors UE', 'Exoneree', 'percent', 0, 'sale', 'export', date '1993-01-01', null, 'CGI, art. 262 I', 'G', 'VATEX-EU-G', 80, 'vat', true, null, false, false, null),
  ('FR', 'FR-S-ICG', 'Livraison intracommunautaire', 'Biens, exoneree', 'percent', 0, 'sale', 'intracom_goods', date '1993-01-01', null, 'CGI, art. 262 ter I', 'K', 'VATEX-EU-IC', 60, 'vat', true, null, false, false, null),
  ('FR', 'FR-S-ICS', 'Service intracommunautaire', 'Autoliquidation par le preneur', 'percent', 0, 'sale', 'intracom_services', date '2010-01-01', null, 'CGI, art. 259-1', 'AE', 'VATEX-EU-AE', 70, 'vat', true, null, false, false, null)
on conflict (country, code) do update set
  name            = excluded.name,
  description     = excluded.description,
  amount_type     = excluded.amount_type,
  amount          = excluded.amount,
  applies_to      = excluded.applies_to,
  treatment       = excluded.treatment,
  valid_from      = excluded.valid_from,
  valid_to        = excluded.valid_to,
  legal_reference = excluded.legal_reference,
  vat_category    = excluded.vat_category,
  exemption_code  = excluded.exemption_code,
  sequence        = excluded.sequence,
  tax_kind        = excluded.tax_kind,
  recoverable     = excluded.recoverable,
  jurisdiction    = excluded.jurisdiction,
  price_include   = excluded.price_include,
  cash_basis      = excluded.cash_basis,
  cash_basis_transition_account_code = excluded.cash_basis_transition_account_code;

insert into tax_posting_templates
  (tax_template_id, document_kind, posting_type, factor_percent, account_code,
   declaration_box, box_factor_percent, report_code, sequence)
select t.id,
       v.document_kind::tax_document_kind,
       v.posting_type::tax_posting_type,
       v.factor_percent::numeric,
       v.account_code::text,
       v.declaration_box::text,
       v.box_factor_percent::numeric,
       v.report_code::text,
       v.sequence::integer
  from (values
    ('FR-P-055', 'invoice', 'tax', 100, '445660', '20', 100, 'FR-CA3', 20),
    ('FR-P-055', 'credit_note', 'tax', 100, '445660', '20', -100, 'FR-CA3', 20),
    ('FR-P-10', 'invoice', 'tax', 100, '445660', '20', 100, 'FR-CA3', 20),
    ('FR-P-10', 'credit_note', 'tax', 100, '445660', '20', -100, 'FR-CA3', 20),
    ('FR-P-20', 'invoice', 'tax', 100, '445660', '20', 100, 'FR-CA3', 20),
    ('FR-P-20', 'credit_note', 'tax', 100, '445660', '20', -100, 'FR-CA3', 20),
    ('FR-P-20-CARB', 'invoice', 'tax', 80, '445660', '20', 80, 'FR-CA3', 20),
    ('FR-P-20-CARB', 'invoice', 'tax_on_base', 20, null, null, 100, null, 30),
    ('FR-P-20-CARB', 'credit_note', 'tax', 80, '445660', '20', -80, 'FR-CA3', 20),
    ('FR-P-20-CARB', 'credit_note', 'tax_on_base', 20, null, null, 100, null, 30),
    ('FR-P-20-I', 'invoice', 'tax', 100, '445662', '19', 100, 'FR-CA3', 20),
    ('FR-P-20-I', 'credit_note', 'tax', 100, '445662', '19', -100, 'FR-CA3', 20),
    ('FR-P-AL-20', 'invoice', 'base', 100, null, '3C', 100, 'FR-CA3', 10),
    ('FR-P-AL-20', 'invoice', 'tax', 100, '445660', '20', 100, 'FR-CA3', 20),
    ('FR-P-AL-20', 'invoice', 'tax', -100, '445200', '08', 100, 'FR-CA3', 30),
    ('FR-P-AL-20', 'credit_note', 'base', 100, null, '3C', -100, 'FR-CA3', 10),
    ('FR-P-AL-20', 'credit_note', 'tax', 100, '445660', '20', -100, 'FR-CA3', 20),
    ('FR-P-AL-20', 'credit_note', 'tax', -100, '445200', '08', -100, 'FR-CA3', 30),
    ('FR-P-ICG-20', 'invoice', 'base', 100, null, '03', 100, 'FR-CA3', 10),
    ('FR-P-ICG-20', 'invoice', 'tax', 100, '445660', '20', 100, 'FR-CA3', 20),
    ('FR-P-ICG-20', 'invoice', 'tax', -100, '445200', '08', 100, 'FR-CA3', 30),
    ('FR-P-ICG-20', 'credit_note', 'base', 100, null, '03', -100, 'FR-CA3', 10),
    ('FR-P-ICG-20', 'credit_note', 'tax', 100, '445660', '20', -100, 'FR-CA3', 20),
    ('FR-P-ICG-20', 'credit_note', 'tax', -100, '445200', '08', -100, 'FR-CA3', 30),
    ('FR-P-ICS-20', 'invoice', 'base', 100, null, '2A', 100, 'FR-CA3', 10),
    ('FR-P-ICS-20', 'invoice', 'tax', 100, '445660', '20', 100, 'FR-CA3', 20),
    ('FR-P-ICS-20', 'invoice', 'tax', -100, '445200', '08', 100, 'FR-CA3', 30),
    ('FR-P-ICS-20', 'credit_note', 'base', 100, null, '2A', -100, 'FR-CA3', 10),
    ('FR-P-ICS-20', 'credit_note', 'tax', 100, '445660', '20', -100, 'FR-CA3', 20),
    ('FR-P-ICS-20', 'credit_note', 'tax', -100, '445200', '08', -100, 'FR-CA3', 30),
    ('FR-P-IMP-20', 'invoice', 'base', 100, null, '3A', 100, 'FR-CA3', 10),
    ('FR-P-IMP-20', 'invoice', 'tax', 100, '445660', '20', 100, 'FR-CA3', 20),
    ('FR-P-IMP-20', 'invoice', 'tax', -100, '445200', '08', 100, 'FR-CA3', 30),
    ('FR-P-IMP-20', 'credit_note', 'base', 100, null, '3A', -100, 'FR-CA3', 10),
    ('FR-P-IMP-20', 'credit_note', 'tax', 100, '445660', '20', -100, 'FR-CA3', 20),
    ('FR-P-IMP-20', 'credit_note', 'tax', -100, '445200', '08', -100, 'FR-CA3', 30),
    ('FR-S-021', 'invoice', 'base', 100, null, '13', 100, 'FR-CA3', 10),
    ('FR-S-021', 'invoice', 'tax', 100, '445710', '13', 100, 'FR-CA3', 20),
    ('FR-S-021', 'credit_note', 'base', 100, null, '13', -100, 'FR-CA3', 10),
    ('FR-S-021', 'credit_note', 'tax', 100, '445710', '13', -100, 'FR-CA3', 20),
    ('FR-S-055', 'invoice', 'base', 100, null, '09', 100, 'FR-CA3', 10),
    ('FR-S-055', 'invoice', 'tax', 100, '445710', '09', 100, 'FR-CA3', 20),
    ('FR-S-055', 'credit_note', 'base', 100, null, '09', -100, 'FR-CA3', 10),
    ('FR-S-055', 'credit_note', 'tax', 100, '445710', '09', -100, 'FR-CA3', 20),
    ('FR-S-10', 'invoice', 'base', 100, null, '9B', 100, 'FR-CA3', 10),
    ('FR-S-10', 'invoice', 'tax', 100, '445710', '9B', 100, 'FR-CA3', 20),
    ('FR-S-10', 'credit_note', 'base', 100, null, '9B', -100, 'FR-CA3', 10),
    ('FR-S-10', 'credit_note', 'tax', 100, '445710', '9B', -100, 'FR-CA3', 20),
    ('FR-S-20', 'invoice', 'base', 100, null, '08', 100, 'FR-CA3', 10),
    ('FR-S-20', 'invoice', 'tax', 100, '445710', '08', 100, 'FR-CA3', 20),
    ('FR-S-20', 'credit_note', 'base', 100, null, '08', -100, 'FR-CA3', 10),
    ('FR-S-20', 'credit_note', 'tax', 100, '445710', '08', -100, 'FR-CA3', 20),
    ('FR-S-AL', 'invoice', 'base', 100, null, '05', 100, 'FR-CA3', 10),
    ('FR-S-AL', 'credit_note', 'base', 100, null, '05', -100, 'FR-CA3', 10),
    ('FR-S-EXP', 'invoice', 'base', 100, null, '04', 100, 'FR-CA3', 10),
    ('FR-S-EXP', 'credit_note', 'base', 100, null, '04', -100, 'FR-CA3', 10),
    ('FR-S-ICG', 'invoice', 'base', 100, null, '06', 100, 'FR-CA3', 10),
    ('FR-S-ICG', 'credit_note', 'base', 100, null, '06', -100, 'FR-CA3', 10),
    ('FR-S-ICS', 'invoice', 'base', 100, null, '05', 100, 'FR-CA3', 10),
    ('FR-S-ICS', 'credit_note', 'base', 100, null, '05', -100, 'FR-CA3', 10)
  ) as v (tax_code, document_kind, posting_type, factor_percent, account_code,
          declaration_box, box_factor_percent, report_code, sequence)
  join tax_templates t on t.country = 'FR' and t.code = v.tax_code
on conflict (tax_template_id, document_kind, posting_type, sequence) do update set
  factor_percent     = excluded.factor_percent,
  account_code       = excluded.account_code,
  declaration_box    = excluded.declaration_box,
  box_factor_percent = excluded.box_factor_percent,
  report_code        = excluded.report_code;

insert into tax_report_templates
  (country, code, name, period, valid_from, valid_to, legal_reference, is_periodic_return)
values
  ('FR', 'FR-CA3', 'Déclaration de TVA 3310-CA3', 'month_or_quarter', date '2022-01-01', null, 'CGI, art. 287 — formulaire 3310-CA3', true)
on conflict (country, code) do update set
  name               = excluded.name,
  period             = excluded.period,
  valid_from         = excluded.valid_from,
  valid_to           = excluded.valid_to,
  legal_reference    = excluded.legal_reference,
  is_periodic_return = excluded.is_periodic_return;

insert into tax_report_box_templates
  (country, report_code, box, kind, name, name_i18n, sequence,
   plus_boxes, minus_boxes, floor_zero, hidden, xml_element, legal_reference)
values
  ('FR', 'FR-CA3', '01', 'total', 'Ventes, prestations de services', '{}'::jsonb, 10, array['08:base', '09:base', '9B:base', '13:base']::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '03', 'base', 'Acquisitions intracommunautaires', '{}'::jsonb, 20, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '2A', 'base', 'Achats de prestations de services intracommunautaires', '{}'::jsonb, 30, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '3A', 'base', 'Importations autoliquidées', '{}'::jsonb, 40, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '3C', 'base', 'Achats de biens ou de prestations auprès d''un assujetti non établi en France', '{}'::jsonb, 50, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '04', 'base', 'Exportations hors Union européenne', '{}'::jsonb, 60, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '05', 'base', 'Autres opérations non imposables', '{}'::jsonb, 70, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '06', 'base', 'Livraisons intracommunautaires', '{}'::jsonb, 80, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '08', 'base', 'Taux normal 20 % — base hors taxe', '{}'::jsonb, 100, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '09', 'base', 'Taux réduit 5,5 % — base hors taxe', '{}'::jsonb, 110, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '9B', 'base', 'Taux réduit 10 % — base hors taxe', '{}'::jsonb, 120, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '13', 'base', 'Taux particulier 2,1 % — base hors taxe', '{}'::jsonb, 130, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '08', 'tax', 'Taux normal 20 % — TVA due', '{}'::jsonb, 140, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '09', 'tax', 'Taux réduit 5,5 % — TVA due', '{}'::jsonb, 150, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '9B', 'tax', 'Taux réduit 10 % — TVA due', '{}'::jsonb, 160, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '13', 'tax', 'Taux particulier 2,1 % — TVA due', '{}'::jsonb, 170, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '16', 'total', 'Total de la TVA brute due', '{}'::jsonb, 200, array['08:tax', '09:tax', '9B:tax', '13:tax']::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '19', 'tax', 'TVA déductible sur immobilisations', '{}'::jsonb, 210, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '20', 'tax', 'TVA déductible sur autres biens et services', '{}'::jsonb, 220, '{}'::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '23', 'total', 'Total de la TVA déductible', '{}'::jsonb, 230, array['19', '20']::text[], '{}'::text[], false, false, null, null),
  ('FR', 'FR-CA3', '28', 'total', 'TVA nette due', '{}'::jsonb, 240, array['16']::text[], array['23']::text[], true, false, null, null),
  ('FR', 'FR-CA3', '25', 'total', 'Crédit de TVA', '{}'::jsonb, 250, array['23']::text[], array['16']::text[], true, false, null, null)
on conflict (country, report_code, box, kind) do update set
  name            = excluded.name,
  name_i18n       = excluded.name_i18n,
  sequence        = excluded.sequence,
  plus_boxes      = excluded.plus_boxes,
  minus_boxes     = excluded.minus_boxes,
  floor_zero      = excluded.floor_zero,
  hidden          = excluded.hidden,
  xml_element     = excluded.xml_element,
  legal_reference = excluded.legal_reference;

insert into country_defaults
  (country, name, currency_code, receivable_code, payable_code, suspense_code,
   rounding_code, retained_earnings_code, sales_account_code, purchase_account_code,
   bank_account_code, cash_account_code, sales_journal_code, purchase_journal_code,
   misc_journal_code, language_default, closing_style, current_year_result_profit_code,
   current_year_result_loss_code, retained_earnings_loss_code, opening_journal_code,
   rounding_method, cash_rounding_unit)
values
  ('FR', 'France', 'EUR', '411000', '401000', '471000', '658000', '110000', '706000', '606300', '512000', '530000', 'SAL', 'PUR', 'MISC', 'fr', 'result_accounts', '120000', '129000', '119000', 'OPN', 'half_up', default)
on conflict (country) do update set
  name                   = excluded.name,
  currency_code          = excluded.currency_code,
  receivable_code        = excluded.receivable_code,
  payable_code           = excluded.payable_code,
  suspense_code          = excluded.suspense_code,
  rounding_code          = excluded.rounding_code,
  retained_earnings_code = excluded.retained_earnings_code,
  sales_account_code     = excluded.sales_account_code,
  purchase_account_code  = excluded.purchase_account_code,
  bank_account_code      = excluded.bank_account_code,
  cash_account_code      = excluded.cash_account_code,
  sales_journal_code     = excluded.sales_journal_code,
  purchase_journal_code  = excluded.purchase_journal_code,
  misc_journal_code      = excluded.misc_journal_code,
  language_default       = excluded.language_default,
  closing_style          = excluded.closing_style,
  current_year_result_profit_code = excluded.current_year_result_profit_code,
  current_year_result_loss_code   = excluded.current_year_result_loss_code,
  retained_earnings_loss_code     = excluded.retained_earnings_loss_code,
  opening_journal_code            = excluded.opening_journal_code,
  rounding_method        = excluded.rounding_method,
  cash_rounding_unit     = excluded.cash_rounding_unit;
